// ═══════════════════════════════════════════════════════════════════════════════
// FILE: js/vocabLevel.js
// NihongoZen — Level-wise Chapter Vocabulary Data (N5 – N1)
//
// Structure:
//   NZChapterVocabWords[level][chapterIndex] = [ { jp, romaji, en }, ... ]
//
// Load BEFORE nz-chapter-vocab.js and nz-vocab-module.js.
// The module merges: chapter metadata from chapters.js + words from this file
// via: NZChapterData[level][i].words = NZChapterVocabWords[level][i]
// ═══════════════════════════════════════════════════════════════════════════════
'use strict';

const NZChapterVocabWords = {

  /* ════════ N5 ════════ */
  N5: [
    /* Ch 1 */  [
        { jp:'せんせい', romaji:'sensei', en:'teacher' },
        { jp:'がくせい', romaji:'gakusei', en:'student' },
        { jp:'かいしゃいん', romaji:'kaishain', en:'company employee' },
        { jp:'いしゃ', romaji:'isha', en:'doctor' },
        { jp:'エンジニア', romaji:'enjinia', en:'engineer' },
        { jp:'だいがく', romaji:'daigaku', en:'university' },
        { jp:'にほん', romaji:'nihon', en:'Japan' },
        { jp:'なまえ', romaji:'namae', en:'name' },
        { jp:'挨拶する', romaji:'aisatsu suru', en:'to greet' },
        { jp:'元気？', romaji:'genki?', en:'How are you?' },
        { jp:'さようなら', romaji:'sayōnara', en:'goodbye' },
        { jp:'バイバイ', romaji:'baibai', en:'bye (fam.)' },
        { jp:'じゃあね', romaji:'jā ne', en:'see you soon' },
        { jp:'さらば', romaji:'saraba', en:'farewell' },
        { jp:'またね', romaji:'mata ne', en:'so long' },
        { jp:'ありがとう', romaji:'arigatō', en:'thank you' },
        { jp:'どうもありがとう', romaji:'dōmo arigatō', en:'thank you very much' },
        { jp:'失礼', romaji:'shitsurei', en:'excuse me' },
        { jp:'私', romaji:'watashi', en:'I/me' },
        { jp:'あなた', romaji:'anata', en:'you' },
        { jp:'彼', romaji:'kare', en:'he' },
        { jp:'彼女', romaji:'kanojo', en:'she' },
        { jp:'私たち', romaji:'watashi tachi', en:'we' },
        { jp:'あなたがた', romaji:'anata ga ta', en:'you (group)' },
        { jp:'彼らは', romaji:'karera wa', en:'they' },
        { jp:'お名前', romaji:'o-namae', en:'your name (formal)' },
        { jp:'名字', romaji:'myōji', en:'surname' },
        { jp:'住所', romaji:'jūsho', en:'address' },
        { jp:'郵便番号', romaji:'yūbin bangō', en:'postal code' },
        { jp:'出生地', romaji:'shusshōchi', en:'place of birth' },
        { jp:'職業', romaji:'shokugyō', en:'occupation' },
        { jp:'既婚', romaji:'kikon', en:'married' },
        { jp:'未婚', romaji:'mikon', en:'single (unmarried)' },
        { jp:'離婚', romaji:'rikon', en:'divorced' },
        { jp:'身分証明書', romaji:'mibun shōmeisho', en:'identity card' },
    ],
    /* Ch 2 */  [
        { jp:'これ', romaji:'kore', en:'this (near speaker)' },
        { jp:'それ', romaji:'sore', en:'that (near listener)' },
        { jp:'あれ', romaji:'are', en:'that over there' },
        { jp:'この', romaji:'kono', en:'this ~' },
        { jp:'その', romaji:'sono', en:'that ~' },
        { jp:'あの', romaji:'ano', en:'that ~ over there' },
        { jp:'ほん', romaji:'hon', en:'book' },
        { jp:'ざっし', romaji:'zasshi', en:'magazine' },
        { jp:'しんぶん', romaji:'shinbun', en:'newspaper' },
        { jp:'かさ', romaji:'kasa', en:'umbrella' },
        { jp:'かばん', romaji:'kaban', en:'bag' },
        { jp:'くつ', romaji:'kutsu', en:'shoes' },
        { jp:'ボールペン', romaji:'bōrupen', en:'ballpoint pen' },
        { jp:'万年筆', romaji:'mannenhitsu', en:'fountain pen' },
        { jp:'鉛筆', romaji:'enpitsu', en:'pencil' },
        { jp:'蛍光ペン', romaji:'keikō pen', en:'highlighter' },
        { jp:'フェルトペン', romaji:'feruto pen', en:'felt-tip pen' },
        { jp:'メモ帳', romaji:'memo chō', en:'notepad' },
        { jp:'手帳', romaji:'techō', en:'agenda/diary' },
        { jp:'定規', romaji:'jōgi', en:'ruler' },
        { jp:'電卓', romaji:'dentaku', en:'calculator' },
        { jp:'消しゴム', romaji:'keshigomu', en:'eraser' },
        { jp:'誰', romaji:'dare', en:'who?' },
        { jp:'何', romaji:'nani', en:'what?' },
        { jp:'どこに', romaji:'doko ni', en:'where?' },
        { jp:'いつ', romaji:'itsu', en:'when?' },
        { jp:'なんで', romaji:'nande', en:'why?' },
        { jp:'どうして', romaji:'dōshite', en:'why? (reason)' },
        { jp:'どうやって', romaji:'dō yatte', en:'how?' },
        { jp:'いくつ', romaji:'ikutsu', en:'how many?' },
        { jp:'いくら', romaji:'ikura', en:'how much?' },
        { jp:'誰のもの', romaji:'dare no mono', en:'whose?' },
    ],
    /* Ch 3 */  [
        { jp:'ここ', romaji:'koko', en:'here' },
        { jp:'そこ', romaji:'soko', en:'there' },
        { jp:'あそこ', romaji:'asoko', en:'over there' },
        { jp:'どこ', romaji:'doko', en:'where' },
        { jp:'デパート', romaji:'depaato', en:'department store' },
        { jp:'スーパー', romaji:'suupaa', en:'supermarket' },
        { jp:'レストラン', romaji:'resutoran', en:'restaurant' },
        { jp:'ぎんこう', romaji:'ginkou', en:'bank' },
        { jp:'えき', romaji:'eki', en:'station' },
        { jp:'びょういん', romaji:'byouin', en:'hospital' },
        { jp:'ほんや', romaji:'hon-ya', en:'bookstore' },
        { jp:'ここで', romaji:'kokode', en:'here' },
        { jp:'そこで', romaji:'sokode', en:'there' },
        { jp:'前に', romaji:'mae ni', en:'in front / before' },
        { jp:'後ろに', romaji:'ushiro ni', en:'behind' },
        { jp:'真っ直ぐに', romaji:'massugu ni', en:'straight' },
        { jp:'今', romaji:'ima', en:'now' },
        { jp:'よく', romaji:'yoku', en:'often' },
        { jp:'普通は', romaji:'futsū wa', en:'usually' },
        { jp:'恐らく', romaji:'osoraku', en:'probably' },
        { jp:'とても', romaji:'totemo', en:'very' },
        { jp:'市、町', romaji:'shi, machi', en:'city' },
        { jp:'首都', romaji:'shuto', en:'capital city' },
        { jp:'村', romaji:'mura', en:'village' },
        { jp:'中心街', romaji:'chūshin gai', en:'downtown' },
        { jp:'郊外', romaji:'kōgai', en:'suburb' },
        { jp:'町外れ', romaji:'machihazure', en:'outskirts' },
        { jp:'市街地図', romaji:'shigai chizu', en:'city map' },
        { jp:'街区', romaji:'gaiku', en:'city block' },
        { jp:'住宅街', romaji:'jūtaku gai', en:'residential block' },
        { jp:'歩行者', romaji:'hokō sha', en:'pedestrian' },
        { jp:'真っ直ぐ', romaji:'massugu', en:'straight ahead' },
        { jp:'右の方に', romaji:'migi no hō ni', en:'to the right' },
        { jp:'左の方に', romaji:'hidari no hō ni', en:'to the left' },
        { jp:'…の隣に', romaji:'… no tonari ni', en:'next to...' },
        { jp:'…の向こう側に', romaji:'… no mukōgawa ni', en:'opposite...' },
        { jp:'…の前に', romaji:'… no mae ni', en:'in front of...' },
        { jp:'…の真ん中に', romaji:'… no mannaka ni', en:'in the center of...' },
        { jp:'…経由で', romaji:'… keiyu de', en:'via...' },
        { jp:'…の中に', romaji:'… no naka ni', en:'inside...' },
        { jp:'…の上に', romaji:'… no ue ni', en:'on top of...' },
    ],
    /* Ch 4 */  [
        { jp:'なんじ', romaji:'nanji', en:'what time?' },
        { jp:'ごぜん', romaji:'gozen', en:'AM / morning' },
        { jp:'ごご', romaji:'gogo', en:'PM / afternoon' },
        { jp:'はん', romaji:'han', en:'half past' },
        { jp:'まいにち', romaji:'mainichi', en:'every day' },
        { jp:'やすみ', romaji:'yasumi', en:'day off / rest' },
        { jp:'今日', romaji:'kyō', en:'today' },
        { jp:'明日', romaji:'ashita', en:'tomorrow' },
        { jp:'昨日', romaji:'kinō', en:'yesterday' },
        { jp:'朝', romaji:'asa', en:'morning' },
        { jp:'正午', romaji:'shōgo', en:'noon' },
        { jp:'夕方', romaji:'yūgata', en:'evening' },
        { jp:'夜', romaji:'yoru', en:'night' },
        { jp:'真夜中', romaji:'mayonaka', en:'midnight' },
        { jp:'午後', romaji:'gogo', en:'afternoon' },
        { jp:'秒', romaji:'byō', en:'second (time)' },
        { jp:'今何時ですか', romaji:'ima nanji desu ka', en:'what time is it?' },
        { jp:'三十分間', romaji:'sanjuppunkan', en:'half an hour' },
        { jp:'何時', romaji:'nanji', en:'what time?' },
        { jp:'…過ぎに', romaji:'… sugi ni', en:'after (time)' },
        { jp:'…から…まで', romaji:'… kara … made', en:'from... to...' },
        { jp:'一時間後に', romaji:'ichijikan go ni', en:'in an hour' },
        { jp:'十五分後に', romaji:'jūgofun go ni', en:'in 15 minutes' },
        { jp:'月曜日', romaji:'getsuyōbi', en:'Monday' },
        { jp:'火曜日', romaji:'kayōbi', en:'Tuesday' },
        { jp:'水曜日', romaji:'suiyōbi', en:'Wednesday' },
        { jp:'木曜日', romaji:'mokuyōbi', en:'Thursday' },
        { jp:'金曜日', romaji:'kinyōbi', en:'Friday' },
        { jp:'土曜日', romaji:'doyōbi', en:'Saturday' },
        { jp:'日曜日', romaji:'nichiyōbi', en:'Sunday' },
        { jp:'明後日', romaji:'asatte', en:'the day after tomorrow' },
        { jp:'一昨日', romaji:'ototoi', en:'the day before yesterday' },
        { jp:'営業日', romaji:'eigyōbi', en:'working day' },
        { jp:'今週', romaji:'konshū', en:'this week' },
        { jp:'来月', romaji:'raigetsu', en:'next month' },
        { jp:'去年', romaji:'kyonen', en:'last year' },
        { jp:'次の', romaji:'tsugi no', en:'next...' },
        { jp:'昨晩', romaji:'sakuban', en:'last night' },
        { jp:'今晩', romaji:'komban', en:'tonight' },
        { jp:'今朝', romaji:'kesa', en:'this morning' },
        { jp:'休日', romaji:'kyūjitsu', en:'day off / holiday' },
        { jp:'間に合って', romaji:'maniatte', en:'on time' },
        { jp:'早過ぎます', romaji:'hayasugimasu', en:'too early' },
    ],
    /* Ch 5 */  [
        { jp:'いくら', romaji:'ikura', en:'how much?' },
        { jp:'たかい', romaji:'takai', en:'expensive' },
        { jp:'やすい', romaji:'yasui', en:'cheap' },
        { jp:'ください', romaji:'kudasai', en:'please give me' },
        { jp:'みせ', romaji:'mise', en:'shop / store' },
        { jp:'えん', romaji:'en', en:'yen' },
        { jp:'お金', romaji:'okane', en:'money' },
        { jp:'銀行', romaji:'ginkō', en:'bank' },
        { jp:'口座', romaji:'kōza', en:'account' },
        { jp:'クレジットカード', romaji:'kurejitto kādo', en:'credit card' },
        { jp:'現金', romaji:'genkin', en:'cash' },
        { jp:'財布', romaji:'saifu', en:'wallet' },
        { jp:'税', romaji:'zei', en:'tax' },
        { jp:'割引', romaji:'waribiki', en:'discount' },
        { jp:'価格', romaji:'kakaku', en:'price' },
        { jp:'両替', romaji:'ryōgae', en:'currency exchange' },
        { jp:'買う', romaji:'kau', en:'to buy' },
        { jp:'買い物に行く', romaji:'kaimono ni iku', en:'to go shopping' },
        { jp:'値札', romaji:'nefuda', en:'price tag' },
        { jp:'安価な', romaji:'anka na', en:'inexpensive' },
        { jp:'高い', romaji:'takai', en:'expensive' },
        { jp:'レジ', romaji:'reji', en:'check out/cash desk' },
        { jp:'試着室', romaji:'shichaku shitsu', en:'fitting room' },
        { jp:'試着する', romaji:'shichaku suru', en:'to try on' },
        { jp:'レンタル', romaji:'rentaru', en:'rental' },
        { jp:'付けで', romaji:'tsuke de', en:'on credit' },
        { jp:'いらっしゃいませ', romaji:'irasshaimase', en:'welcome to a shop' },
        { jp:'ちょっと見ているだけです', romaji:'chotto mite iru dake desu', en:'I am just looking' },
        { jp:'これ下さい', romaji:'kore kudasai', en:'I will take this one' },
        { jp:'説明書は入っていますか', romaji:'setsumaisho wa haitte imasu ka', en:'does it come with instructions?' },
        { jp:'ちょっと高過ぎます', romaji:'chotto taka sugimasu', en:'it is too expensive' },
        { jp:'ビニール袋ありますか', romaji:'binīru bukuro arimasu ka', en:'do you have a bag?' },
        { jp:'プレゼントですから包んで下さい', romaji:'purezento desu kara tsutsunde kudasai', en:'please gift wrap it' },
        { jp:'袋は大丈夫です', romaji:'fukuro wa daijōbu desu', en:'I do not need a bag' },
        { jp:'材料は何ですか', romaji:'zairyō wa nan desu ka', en:'what is in it?' },
        { jp:'試着出来ますか', romaji:'shichaku dekimasu ka', en:'can I try this on?' },
    ],
    /* Ch 6 */  [
        { jp:'おきます', romaji:'okimasu', en:'to wake up' },
        { jp:'ねます', romaji:'nemasu', en:'to sleep / go to bed' },
        { jp:'しごと', romaji:'shigoto', en:'work' },
        { jp:'でかけます', romaji:'dekakemasu', en:'to go out' },
        { jp:'かえります', romaji:'kaerimasu', en:'to return home' },
        { jp:'べんきょうします', romaji:'benkyou shimasu', en:'to study' },
        { jp:'はたらきます', romaji:'hatarakimasu', en:'to work' },
        { jp:'やすみます', romaji:'yasumimasu', en:'to rest / take a day off' },
        { jp:'同意する', romaji:'dōi suru', en:'to agree' },
        { jp:'謝る', romaji:'ayamaru', en:'to apologize' },
        { jp:'始める', romaji:'hajimeru', en:'to begin' },
        { jp:'変える', romaji:'kaeru', en:'to change' },
        { jp:'選択する', romaji:'sentaku suru', en:'to choose' },
        { jp:'料理をする', romaji:'ryōri wo suru', en:'to cook' },
        { jp:'泣く', romaji:'naku', en:'to cry' },
        { jp:'だます', romaji:'damasu', en:'to deceive' },
        { jp:'見つける', romaji:'mitsukeru', en:'to find' },
        { jp:'飛ぶ', romaji:'tobu', en:'to fly' },
    ],
    /* Ch 7 */  [
        { jp:'えいが', romaji:'eiga', en:'movie' },
        { jp:'おんがく', romaji:'ongaku', en:'music' },
        { jp:'スポーツ', romaji:'supootsu', en:'sport' },
        { jp:'よみます', romaji:'yomimasu', en:'to read' },
        { jp:'ききます', romaji:'kikimasu', en:'to listen' },
        { jp:'みます', romaji:'mimasu', en:'to watch / see' },
        { jp:'かきます', romaji:'kakimasu', en:'to write' },
        { jp:'はなします', romaji:'hanashimasu', en:'to speak / talk' },
        { jp:'たべます', romaji:'tabemasu', en:'to eat' },
        { jp:'のみます', romaji:'nomimasu', en:'to drink' },
        { jp:'あそびます', romaji:'asobimasu', en:'to play / hang out' },
        { jp:'しゃしん', romaji:'shashin', en:'photograph' },
        { jp:'テレビ', romaji:'terebi', en:'television' },
        { jp:'ラジオ', romaji:'rajio', en:'radio' },
        { jp:'ほん', romaji:'hon', en:'book' },
    ],
    /* Ch 8 */  [
        { jp:'すき', romaji:'suki', en:'like / fond of' },
        { jp:'きらい', romaji:'kirai', en:'dislike' },
        { jp:'じょうず', romaji:'jouzu', en:'good at / skilled' },
        { jp:'へた', romaji:'heta', en:'bad at / unskilled' },
        { jp:'たのしい', romaji:'tanoshii', en:'fun / enjoyable' },
        { jp:'むずかしい', romaji:'muzukashii', en:'difficult' },
        { jp:'おもしろい', romaji:'omoshiroi', en:'interesting' },
        { jp:'つまらない', romaji:'tsumaranai', en:'boring' },
        { jp:'にほんご', romaji:'nihongo', en:'Japanese language' },
        { jp:'えいご', romaji:'eigo', en:'English language' },
        { jp:'言語', romaji:'gengo', en:'language' },
        { jp:'外国語', romaji:'gaikoku go', en:'foreign language' },
        { jp:'辞書', romaji:'jisho', en:'dictionary' },
        { jp:'翻訳', romaji:'honyaku', en:'translation' },
        { jp:'発音', romaji:'hatsuon', en:'pronunciation' },
        { jp:'文法', romaji:'bunpō', en:'grammar' },
        { jp:'単語', romaji:'tango', en:'word' },
        { jp:'学ぶ', romaji:'manabu', en:'to learn' },
        { jp:'速く', romaji:'hayaku', en:'fast' },
        { jp:'ゆっくり', romaji:'yukkuri', en:'slowly' },
        { jp:'白い', romaji:'shiroi', en:'white' },
        { jp:'黒い', romaji:'kuroi', en:'black' },
        { jp:'赤い', romaji:'akai', en:'red' },
        { jp:'青い', romaji:'aoi', en:'blue' },
        { jp:'緑の', romaji:'midori no', en:'green' },
        { jp:'黄色い', romaji:'kīroi', en:'yellow' },
        { jp:'ピンクの', romaji:'pinku no', en:'pink' },
        { jp:'オレンジの', romaji:'orenji no', en:'orange' },
        { jp:'紫色の', romaji:'murasaki iro no', en:'violet' },
        { jp:'茶色の', romaji:'chairo no', en:'brown' },
    ],
    /* Ch 9 */  [
        { jp:'でんしゃ', romaji:'densha', en:'train' },
        { jp:'バス', romaji:'basu', en:'bus' },
        { jp:'タクシー', romaji:'takushii', en:'taxi' },
        { jp:'じてんしゃ', romaji:'jitensha', en:'bicycle' },
        { jp:'ひこうき', romaji:'hikouki', en:'airplane' },
        { jp:'いきます', romaji:'ikimasu', en:'to go' },
        { jp:'きます', romaji:'kimasu', en:'to come' },
        { jp:'のります', romaji:'norimasu', en:'to ride / board' },
        { jp:'おります', romaji:'orimasu', en:'to get off' },
        { jp:'この電車はどこへ行きますか', romaji:'kono densha wa doko e ikimasu ka', en:'where does this train go?' },
        { jp:'この席は空いていますか', romaji:'kono seki wa aite imasu ka', en:'is this seat free?' },
        { jp:'これは指定席ですか', romaji:'kore wa shiteiseki desu ka', en:'is this seat reserved?' },
        { jp:'予約しました', romaji:'yoyaku shimashita', en:'I have reserved...' },
        { jp:'今どのへんですか', romaji:'ima dono hen desu ka', en:'where are we now?' },
        { jp:'この切符は往復ですか', romaji:'kono kippu wa ōfuku desu ka', en:'is this a return ticket?' },
        { jp:'この切符で乗り換えられますか', romaji:'kono kippu de norikaerare masu ka', en:'can I change on this ticket?' },
        { jp:'この切符はいつまで有効ですか', romaji:'kono kippu wa itsu made yūkō desu ka', en:'how long is this ticket valid?' },
        { jp:'JRパスを持っています', romaji:'JR pasu wo motte imasu', en:'I have a Japan Rail Pass' },
        { jp:'案内所はどこですか', romaji:'annaijo wa doko desu ka', en:'where is the information desk?' },
        { jp:'通勤列車', romaji:'tsūkin ressha', en:'suburban train' },
        { jp:'高速鉄道', romaji:'kōsoku tetsudō', en:'express train' },
        { jp:'各駅列車', romaji:'kaku-eki ressha', en:'slow train' },
        { jp:'ディーゼル機関車', romaji:'dīzeru kikan sha', en:'diesel locomotive' },
        { jp:'蒸気機関車', romaji:'jōki kikan sha', en:'steam engine' },
        { jp:'客車', romaji:'kyakusha', en:'passenger car' },
        { jp:'食堂車', romaji:'shokudō sha', en:'dining car' },
        { jp:'寝台車', romaji:'shin-digh-sha', en:'sleeping car' },
        { jp:'レール', romaji:'rēru', en:'rails' },
        { jp:'鉄道', romaji:'tetsudō', en:'railroad' },
        { jp:'空車', romaji:'kūsha', en:'taxi available / for hire' },
        { jp:'満車', romaji:'mansha', en:'taxi full / booked' },
        { jp:'タクシーを呼んで下さい', romaji:'takushī o yonde kudasai', en:'could you call me a taxi?' },
        { jp:'急いでいるんですが', romaji:'isoide irun desu ga', en:'I am in a hurry' },
        { jp:'もっと速く行ってください', romaji:'motto hayaku itte kudasai', en:'could you speed up?' },
        { jp:'ゆっくり行ってください', romaji:'yukkuri itte kudasai', en:'could you slow down?' },
        { jp:'他の道を取って下さい', romaji:'hoka no michi o totte kudasai', en:'take a different route' },
        { jp:'ここで下ろして下さい', romaji:'koko de oroshite kudasai', en:'let me out here please' },
        { jp:'左に曲がって下さい', romaji:'hidari ni magatte kudasai', en:'turn left' },
        { jp:'右に曲がって下さい', romaji:'migi ni magatte kudasai', en:'turn right' },
    ],
    /* Ch 10 */  [
        { jp:'まち', romaji:'machi', en:'town / city' },
        { jp:'しずか', romaji:'shizuka', en:'quiet / peaceful' },
        { jp:'にぎやか', romaji:'nigiyaka', en:'lively / bustling' },
        { jp:'ふるい', romaji:'furui', en:'old' },
        { jp:'あたらしい', romaji:'atarashii', en:'new' },
        { jp:'おおきい', romaji:'ookii', en:'big / large' },
        { jp:'ちいさい', romaji:'chiisai', en:'small / little' },
        { jp:'きれい', romaji:'kirei', en:'beautiful / clean' },
        { jp:'やま', romaji:'yama', en:'mountain' },
        { jp:'うみ', romaji:'umi', en:'sea / ocean' },
        { jp:'海', romaji:'umi', en:'sea' },
        { jp:'海洋', romaji:'kaiyō', en:'ocean' },
        { jp:'川', romaji:'kawa', en:'river' },
        { jp:'湖', romaji:'mizūmi', en:'lake' },
        { jp:'山', romaji:'yama', en:'mountain' },
        { jp:'島', romaji:'shima', en:'island' },
        { jp:'砂漠', romaji:'sabaku', en:'desert' },
        { jp:'森林', romaji:'shinrin', en:'forest' },
        { jp:'平原', romaji:'heigen', en:'plain' },
        { jp:'火山', romaji:'kazan', en:'volcano' },
        { jp:'市、町', romaji:'shi, machi', en:'city' },
        { jp:'首都', romaji:'shuto', en:'capital city' },
        { jp:'村', romaji:'mura', en:'village' },
        { jp:'中心街', romaji:'chūshin gai', en:'downtown' },
        { jp:'郊外', romaji:'kōgai', en:'suburb' },
        { jp:'町外れ', romaji:'machihazure', en:'outskirts' },
        { jp:'市街地図', romaji:'shigai chizu', en:'city map' },
        { jp:'街区', romaji:'gaiku', en:'city block' },
        { jp:'住宅街', romaji:'jūtaku gai', en:'residential block' },
        { jp:'歩行者', romaji:'hokō sha', en:'pedestrian' },
    ],
    /* Ch 11 */  [
        { jp:'うえ', romaji:'ue', en:'above / up' },
        { jp:'した', romaji:'shita', en:'below / down' },
        { jp:'みぎ', romaji:'migi', en:'right' },
        { jp:'ひだり', romaji:'hidari', en:'left' },
        { jp:'となり', romaji:'tonari', en:'next to' },
        { jp:'まえ', romaji:'mae', en:'in front' },
        { jp:'うしろ', romaji:'ushiro', en:'behind' },
        { jp:'なか', romaji:'naka', en:'inside' },
        { jp:'そと', romaji:'soto', en:'outside' },
        { jp:'ビル', romaji:'biru', en:'building' },
        { jp:'かい', romaji:'kai', en:'floor (counter)' },
        { jp:'へや', romaji:'heya', en:'room' },
        { jp:'アパート', romaji:'apāto', en:'apartment' },
        { jp:'寝室', romaji:'shinshitsu', en:'bedroom' },
        { jp:'台所', romaji:'daidokoro', en:'kitchen' },
        { jp:'浴室', romaji:'yokushitsu', en:'bathroom' },
        { jp:'居間', romaji:'ima', en:'living room' },
        { jp:'天井', romaji:'tenjō', en:'ceiling' },
        { jp:'床', romaji:'yuka', en:'floor' },
        { jp:'窓', romaji:'mado', en:'window' },
        { jp:'ドア', romaji:'doa', en:'door' },
        { jp:'テーブル', romaji:'tēburu', en:'table' },
    ],
    /* Ch 12 */  [
        { jp:'かいます', romaji:'kaimasu', en:'to buy' },
        { jp:'うります', romaji:'urimasu', en:'to sell' },
        { jp:'もらいます', romaji:'moraimasu', en:'to receive' },
        { jp:'あげます', romaji:'agemasu', en:'to give' },
        { jp:'みせます', romaji:'misemasu', en:'to show' },
        { jp:'いろ', romaji:'iro', en:'color' },
        { jp:'サイズ', romaji:'saizu', en:'size' },
        { jp:'洋服', romaji:'yōfuku', en:'clothes' },
        { jp:'オーバーコート', romaji:'ōbā kōto', en:'overcoat' },
        { jp:'毛皮のコート', romaji:'kegawa no kōto', en:'fur coat' },
        { jp:'ダウンコート', romaji:'daun kōto', en:'down coat' },
        { jp:'ジャケット', romaji:'jaketto', en:'jacket (leather)' },
        { jp:'レインコート', romaji:'reinkōto', en:'raincoat' },
        { jp:'防水の', romaji:'bōsui no', en:'waterproof' },
        { jp:'ワイシャツ', romaji:'waishatsu', en:'shirt' },
        { jp:'ズボン', romaji:'zubon', en:'pants/trousers' },
        { jp:'ジーンズ', romaji:'jīnzu', en:'jeans' },
        { jp:'靴', romaji:'kutsu', en:'shoes' },
        { jp:'アンクルブーツ', romaji:'ankuru būtsu', en:'ankle boots' },
        { jp:'パンプス', romaji:'panpusu', en:'shoes (low-heeled)' },
        { jp:'ブーツ', romaji:'būtsu', en:'boots' },
        { jp:'スリッパ', romaji:'surippa', en:'slippers' },
        { jp:'スニーカー', romaji:'sunīkā', en:'sneakers' },
        { jp:'サンダル', romaji:'sandaru', en:'sandals' },
        { jp:'テニスシューズ', romaji:'tenisu shūzu', en:'tennis shoes' },
        { jp:'かかと', romaji:'kakato', en:'heel' },
        { jp:'靴ひも', romaji:'kutsu himo', en:'shoestring' },
    ],
    /* Ch 13 */  [
        { jp:'きのう', romaji:'kinou', en:'yesterday' },
        { jp:'きょう', romaji:'kyou', en:'today' },
        { jp:'あした', romaji:'ashita', en:'tomorrow' },
        { jp:'せんしゅう', romaji:'senshuu', en:'last week' },
        { jp:'らいしゅう', romaji:'raishuu', en:'next week' },
        { jp:'こうえん', romaji:'kouen', en:'park' },
        { jp:'うみ', romaji:'umi', en:'sea / ocean' },
        { jp:'かわ', romaji:'kawa', en:'river' },
        { jp:'たのしかった', romaji:'tanoshikatta', en:'was fun' },
        { jp:'よかった', romaji:'yokatta', en:'was good' },
        { jp:'休暇で行きます', romaji:'kyūka de ikimasu', en:'I am going on vacation' },
        { jp:'出張です', romaji:'shutchō desu', en:'I am on a business trip' },
        { jp:'何も申告する物はありません', romaji:'nani mo shinkoku suru mono wa arimasen', en:'I have nothing to declare' },
        { jp:'領収書です', romaji:'ryōshūsho desu', en:'here is the receipt' },
        { jp:'輸入税はいくらですか', romaji:'yunyūzei wa ikura desu ka', en:'how much is the import tax?' },
        { jp:'ロッカーはどこですか', romaji:'rokkā wa doko desu ka', en:'where are the luggage lockers?' },
        { jp:'カバンが壊れています', romaji:'kaban ga kowarete imasu', en:'my suitcase is damaged' },
        { jp:'成人の日', romaji:'seijin no hi', en:'Coming of Age Day' },
        { jp:'建国記念日', romaji:'kenkoku kinenbi', en:'National Foundation Day' },
        { jp:'春分の日', romaji:'shunbun no hi', en:'Vernal Equinox Day' },
        { jp:'憲法記念日', romaji:'kenpō kinenbi', en:'Constitution Day' },
        { jp:'海の日', romaji:'umi no hi', en:'Marine Day' },
        { jp:'敬老の日', romaji:'keirō no hi', en:'Respect for the Aged Day' },
        { jp:'秋分の日', romaji:'shūbun no hi', en:'Autumnal Equinox Day' },
        { jp:'体育の日', romaji:'taiiku no hi', en:'Health-Sports Day' },
        { jp:'文化の日', romaji:'bunka no hi', en:'Culture Day' },
        { jp:'勤労感謝の日', romaji:'kinrō kansha no hi', en:'Thanksgiving Day' },
    ],
    /* Ch 14 */  [
        { jp:'できます', romaji:'dekimasu', en:'can do / is possible' },
        { jp:'できません', romaji:'dekimasen', en:'cannot do' },
        { jp:'およぎます', romaji:'oyogimasu', en:'to swim' },
        { jp:'うたいます', romaji:'utaimasu', en:'to sing' },
        { jp:'おどります', romaji:'odorimasu', en:'to dance' },
        { jp:'りょうりします', romaji:'ryouri shimasu', en:'to cook' },
        { jp:'うんてんします', romaji:'unten shimasu', en:'to drive' },
        { jp:'スキー', romaji:'sukii', en:'skiing' },
        { jp:'ゴルフ', romaji:'gorufu', en:'golf' },
        { jp:'テニス', romaji:'tenisu', en:'tennis' },
        { jp:'サッカー', romaji:'sakkaa', en:'soccer / football' },
        { jp:'やきゅう', romaji:'yakyuu', en:'baseball' },
        { jp:'ピアノ', romaji:'piano', en:'piano' },
        { jp:'ギター', romaji:'gitaa', en:'guitar' },
    ],
    /* Ch 15 */  [
        { jp:'たんじょうび', romaji:'tanjoubi', en:'birthday' },
        { jp:'なんがつ', romaji:'nangatsu', en:'what month?' },
        { jp:'なんにち', romaji:'nannichi', en:'what day?' },
        { jp:'いつ', romaji:'itsu', en:'when?' },
        { jp:'ことし', romaji:'kotoshi', en:'this year' },
        { jp:'きょねん', romaji:'kyonen', en:'last year' },
        { jp:'らいねん', romaji:'rainen', en:'next year' },
        { jp:'おめでとうございます', romaji:'omedetou gozaimasu', en:'congratulations' },
        { jp:'なんさい', romaji:'nansai', en:'how old?' },
        { jp:'〜さい', romaji:'~sai', en:'... years old' },
        { jp:'一月', romaji:'ichigatsu', en:'January' },
        { jp:'二月', romaji:'nigatsu', en:'February' },
        { jp:'三月', romaji:'sangatsu', en:'March' },
        { jp:'四月', romaji:'shigatsu', en:'April' },
        { jp:'五月', romaji:'gogatsu', en:'May' },
        { jp:'六月', romaji:'rokugatsu', en:'June' },
        { jp:'七月', romaji:'shichigatsu', en:'July' },
        { jp:'八月', romaji:'hachigatsu', en:'August' },
        { jp:'九月', romaji:'kugatsu', en:'September' },
        { jp:'十月', romaji:'jūgatsu', en:'October' },
        { jp:'ゼロ', romaji:'zero', en:'zero' },
        { jp:'一', romaji:'ichi', en:'one' },
        { jp:'二', romaji:'ni', en:'two' },
        { jp:'三', romaji:'san', en:'three' },
        { jp:'四', romaji:'yon', en:'four' },
        { jp:'五', romaji:'go', en:'five' },
        { jp:'六', romaji:'roku', en:'six' },
        { jp:'七', romaji:'nana', en:'seven' },
        { jp:'八', romaji:'hachi', en:'eight' },
        { jp:'九', romaji:'kyū', en:'nine' },
    ],
    /* Ch 16 */  [
        { jp:'まっすぐ', romaji:'massugu', en:'straight ahead' },
        { jp:'みぎにまがります', romaji:'migi ni magarimasu', en:'turn right' },
        { jp:'ひだりにまがります', romaji:'hidari ni magarimasu', en:'turn left' },
        { jp:'しんごう', romaji:'shingou', en:'traffic light' },
        { jp:'こうさてん', romaji:'kousaten', en:'intersection' },
        { jp:'はし', romaji:'hashi', en:'bridge' },
        { jp:'とおり', romaji:'toori', en:'street / road' },
        { jp:'ちかてつ', romaji:'chikatetsu', en:'subway' },
        { jp:'あるきます', romaji:'arukimasu', en:'to walk' },
        { jp:'わかります', romaji:'wakarimasu', en:'to understand' },
        { jp:'どのくらい', romaji:'dono kurai', en:'how far / how long?' },
        { jp:'真っ直ぐ', romaji:'massugu', en:'straight ahead' },
        { jp:'右の方に', romaji:'migi no hō ni', en:'to the right' },
        { jp:'左の方に', romaji:'hidari no hō ni', en:'to the left' },
        { jp:'…の隣に', romaji:'… no tonari ni', en:'next to...' },
        { jp:'…の向こう側に', romaji:'… no mukōgawa ni', en:'opposite...' },
        { jp:'…の前に', romaji:'… no mae ni', en:'in front of...' },
        { jp:'…の真ん中に', romaji:'… no mannaka ni', en:'in the center of...' },
        { jp:'…経由で', romaji:'… keiyu de', en:'via...' },
        { jp:'…の中に', romaji:'… no naka ni', en:'inside...' },
        { jp:'…の上に', romaji:'… no ue ni', en:'on top of...' },
    ],
    /* Ch 17 */  [
        { jp:'あげます', romaji:'agemasu', en:'to give (to others)' },
        { jp:'もらいます', romaji:'moraimasu', en:'to receive' },
        { jp:'くれます', romaji:'kuremasu', en:'to give (to me)' },
        { jp:'プレゼント', romaji:'purezento', en:'present / gift' },
        { jp:'てがみ', romaji:'tegami', en:'letter' },
        { jp:'おみやげ', romaji:'omiyage', en:'souvenir' },
        { jp:'ありがとうございます', romaji:'arigatou gozaimasu', en:'thank you very much' },
        { jp:'はな', romaji:'hana', en:'flower' },
        { jp:'ケーキ', romaji:'keeki', en:'cake' },
        { jp:'おかし', romaji:'okashi', en:'sweets / confectionery' },
        { jp:'ほしい', romaji:'hoshii', en:'want (something)' },
        { jp:'いらない', romaji:'iranai', en:'don\'t need / don\'t want' },
    ],
    /* Ch 18 */  [
        { jp:'てんき', romaji:'tenki', en:'weather' },
        { jp:'はれ', romaji:'hare', en:'sunny / clear' },
        { jp:'くもり', romaji:'kumori', en:'cloudy' },
        { jp:'あめ', romaji:'ame', en:'rain' },
        { jp:'ゆき', romaji:'yuki', en:'snow' },
        { jp:'あつい', romaji:'atsui', en:'hot' },
        { jp:'さむい', romaji:'samui', en:'cold' },
        { jp:'すずしい', romaji:'suzushii', en:'cool' },
        { jp:'あたたかい', romaji:'atatakai', en:'warm' },
        { jp:'かぜ', romaji:'kaze', en:'wind' },
        { jp:'天気', romaji:'tenki', en:'weather' },
        { jp:'雨', romaji:'ame', en:'rain' },
        { jp:'雪', romaji:'yuki', en:'snow' },
        { jp:'雲', romaji:'kumo', en:'cloud' },
        { jp:'風', romaji:'kaze', en:'wind' },
        { jp:'霧', romaji:'kiri', en:'fog' },
        { jp:'雷', romaji:'kaminari', en:'thunder' },
        { jp:'嵐', romaji:'arashi', en:'storm' },
        { jp:'台風', romaji:'taifū', en:'typhoon' },
        { jp:'地震', romaji:'jishin', en:'earthquake' },
        { jp:'天気がくずれます', romaji:'tenki ga kuzuremasu', en:'weather is changing' },
        { jp:'雨になりますか', romaji:'ame ni narimasu ka', en:'is it going to rain?' },
        { jp:'雪になりますか', romaji:'yuki ni narimasu ka', en:'is it going to snow?' },
        { jp:'嵐になりますか', romaji:'arashi ni narimasu ka', en:'will there be a storm?' },
        { jp:'天気予報', romaji:'tenki yohō', en:'weather forecast' },
        { jp:'薄ら寒い', romaji:'usurāsamui', en:'chilly' },
        { jp:'快晴', romaji:'kaisei', en:'clear sky' },
        { jp:'蒸し暑い', romaji:'mushiatsui', en:'muggy' },
        { jp:'梅雨', romaji:'tsuyu', en:'rainy season' },
        { jp:'にわか雨', romaji:'niwaka ame', en:'shower' },
        { jp:'春', romaji:'haru', en:'spring' },
        { jp:'夏', romaji:'natsu', en:'summer' },
        { jp:'秋', romaji:'aki', en:'autumn' },
        { jp:'冬', romaji:'fuyu', en:'winter' },
    ],
    /* Ch 19 */  [
        { jp:'ごはん', romaji:'gohan', en:'rice / meal' },
        { jp:'パン', romaji:'pan', en:'bread' },
        { jp:'たまご', romaji:'tamago', en:'egg' },
        { jp:'さかな', romaji:'sakana', en:'fish' },
        { jp:'にく', romaji:'niku', en:'meat' },
        { jp:'やさい', romaji:'yasai', en:'vegetables' },
        { jp:'くだもの', romaji:'kudamono', en:'fruit' },
        { jp:'おいしい', romaji:'oishii', en:'delicious' },
        { jp:'まずい', romaji:'mazui', en:'bad tasting' },
        { jp:'からい', romaji:'karai', en:'spicy' },
        { jp:'あまい', romaji:'amai', en:'sweet' },
        { jp:'料理', romaji:'ryōri', en:'dish / cuisine' },
        { jp:'レシピ', romaji:'reshipi', en:'recipe' },
        { jp:'サラダ', romaji:'sarada', en:'salad' },
        { jp:'スープ', romaji:'sūpu', en:'soup' },
        { jp:'サンドイッチ', romaji:'sandoicchi', en:'sandwich' },
        { jp:'目玉焼き', romaji:'medamayaki', en:'fried eggs' },
        { jp:'ハンバーガー', romaji:'hanbāgā', en:'hamburger' },
        { jp:'ビーフステーキ', romaji:'bīfusutēki', en:'beefsteak' },
        { jp:'スパゲッティ', romaji:'supagetti', en:'spaghetti' },
        { jp:'ピザ', romaji:'piza', en:'pizza' },
        { jp:'メニュー', romaji:'menyū', en:'menu' },
        { jp:'レストラン', romaji:'resutoran', en:'restaurant' },
        { jp:'朝食', romaji:'chōshoku', en:'breakfast' },
        { jp:'昼食', romaji:'chūshoku', en:'lunch' },
        { jp:'夕食', romaji:'yūshoku', en:'dinner' },
        { jp:'ウェイター', romaji:'weitā', en:'waiter' },
        { jp:'お勘定', romaji:'okanjō', en:'the bill' },
        { jp:'チップ', romaji:'chippu', en:'tip' },
        { jp:'食べる', romaji:'taberu', en:'to eat' },
        { jp:'ウェートレス', romaji:'wētoresu', en:'waitress' },
        { jp:'水', romaji:'mizu', en:'water' },
        { jp:'ミネラルウォーター', romaji:'mineraru wōtā', en:'mineral water' },
        { jp:'ジュース', romaji:'jūsu', en:'juice' },
        { jp:'ビール', romaji:'bīru', en:'beer' },
        { jp:'ワイン', romaji:'wain', en:'wine' },
        { jp:'コーヒー', romaji:'kōhī', en:'coffee' },
        { jp:'茶', romaji:'cha', en:'tea' },
        { jp:'緑茶', romaji:'ryoku cha', en:'green tea' },
        { jp:'紅茶', romaji:'kō cha', en:'black tea' },
        { jp:'ウイスキー', romaji:'uisukī', en:'whisky' },
    ],
    /* Ch 20 */  [
        { jp:'かぞく', romaji:'kazoku', en:'family' },
        { jp:'りょうしん', romaji:'ryoushin', en:'parents' },
        { jp:'しゃしん', romaji:'shashin', en:'photograph' },
        { jp:'きょうだい', romaji:'kyoudai', en:'siblings' },
        { jp:'ひとりっこ', romaji:'hitorikko', en:'only child' },
        { jp:'なんにんかぞく', romaji:'nannin kazoku', en:'how many in family?' },
        { jp:'名前', romaji:'namae', en:'name' },
        { jp:'誕生日', romaji:'tanjō bi', en:'date of birth' },
        { jp:'国籍', romaji:'kokuseki', en:'nationality' },
        { jp:'母親', romaji:'hahaoya', en:'mother' },
        { jp:'父親', romaji:'chichioya', en:'father' },
        { jp:'息子', romaji:'musuko', en:'son' },
        { jp:'娘', romaji:'musume', en:'daughter' },
        { jp:'兄', romaji:'ani', en:'elder brother' },
        { jp:'妹', romaji:'imōto', en:'younger sister' },
        { jp:'祖母', romaji:'sobo', en:'grandmother' },
        { jp:'友情', romaji:'yūjō', en:'friendship' },
        { jp:'パートナー', romaji:'pātonā', en:'partner' },
        { jp:'長', romaji:'chō', en:'boss/chief' },
        { jp:'上司', romaji:'jōshi', en:'superior' },
        { jp:'部下', romaji:'buka', en:'subordinate' },
        { jp:'知り合い', romaji:'shiriai', en:'acquaintance' },
        { jp:'クラスメート', romaji:'kurasumēto', en:'classmate' },
    ],
    /* Ch 21 */  [
        { jp:'びょうき', romaji:'byouki', en:'illness / sick' },
        { jp:'くすり', romaji:'kusuri', en:'medicine' },
        { jp:'いたい', romaji:'itai', en:'painful / it hurts' },
        { jp:'ねつ', romaji:'netsu', en:'fever' },
        { jp:'かぜ', romaji:'kaze', en:'cold (illness)' },
        { jp:'いしゃにいきます', romaji:'isha ni ikimasu', en:'to go to the doctor' },
        { jp:'だいじょうぶ', romaji:'daijoubu', en:'okay / all right' },
        { jp:'病気', romaji:'byōki', en:'sickness' },
        { jp:'健康', romaji:'kenkō', en:'health' },
        { jp:'風邪', romaji:'kaze', en:'cold (illness)' },
        { jp:'発熱', romaji:'hatsunetsu', en:'fever' },
        { jp:'咳', romaji:'seki', en:'cough' },
        { jp:'アレルギー', romaji:'arerugī', en:'allergy' },
        { jp:'糖尿病', romaji:'tōnyō byō', en:'diabetes' },
        { jp:'骨折', romaji:'kossetsu', en:'fracture' },
        { jp:'手術', romaji:'shujutsu', en:'surgery' },
        { jp:'注射', romaji:'chūsha', en:'injection' },
        { jp:'頭', romaji:'atama', en:'head' },
        { jp:'顔', romaji:'kao', en:'face' },
        { jp:'鼻', romaji:'hana', en:'nose' },
        { jp:'口', romaji:'kuchi', en:'mouth' },
        { jp:'眼', romaji:'me', en:'eye' },
        { jp:'耳', romaji:'mimi', en:'ear' },
        { jp:'歯', romaji:'ha', en:'tooth' },
        { jp:'舌', romaji:'shita', en:'tongue' },
        { jp:'首', romaji:'kubi', en:'neck' },
        { jp:'喉', romaji:'nodo', en:'throat' },
    ],
    /* Ch 22 */  [
        { jp:'いえ', romaji:'ie', en:'house / home' },
        { jp:'へや', romaji:'heya', en:'room' },
        { jp:'だいどころ', romaji:'daidokoro', en:'kitchen' },
        { jp:'おふろ', romaji:'ofuro', en:'bath' },
        { jp:'にわ', romaji:'niwa', en:'garden' },
        { jp:'おいでください', romaji:'oide kudasai', en:'please come' },
        { jp:'あそびにきます', romaji:'asobi ni kimasu', en:'to come to visit' },
        { jp:'アパート', romaji:'apāto', en:'apartment' },
        { jp:'寝室', romaji:'shinshitsu', en:'bedroom' },
        { jp:'台所', romaji:'daidokoro', en:'kitchen' },
        { jp:'浴室', romaji:'yokushitsu', en:'bathroom' },
        { jp:'居間', romaji:'ima', en:'living room' },
        { jp:'天井', romaji:'tenjō', en:'ceiling' },
        { jp:'床', romaji:'yuka', en:'floor' },
        { jp:'窓', romaji:'mado', en:'window' },
        { jp:'ドア', romaji:'doa', en:'door' },
        { jp:'テーブル', romaji:'tēburu', en:'table' },
        { jp:'冷蔵庫', romaji:'reizōko', en:'refrigerator' },
        { jp:'電子レンジ', romaji:'denshi renji', en:'microwave' },
        { jp:'オーブン', romaji:'ōbun', en:'oven' },
        { jp:'食器洗い機', romaji:'shokkiarai ki', en:'dishwasher' },
        { jp:'トースター', romaji:'tōsutā', en:'toaster' },
        { jp:'コーヒーメーカー', romaji:'kōhī mēkā', en:'coffee maker' },
        { jp:'やかん', romaji:'yakan', en:'kettle' },
        { jp:'フライパン', romaji:'furaipan', en:'frying pan' },
        { jp:'鍋', romaji:'nabe', en:'pot' },
        { jp:'包丁', romaji:'hōchō', en:'kitchen knife' },
        { jp:'蛇口', romaji:'jaguchi', en:'tap/faucet' },
        { jp:'温水', romaji:'onsui', en:'hot water' },
        { jp:'冷水', romaji:'reisui', en:'cold water' },
        { jp:'シャワーを浴びる', romaji:'shawā wo abiru', en:'to take a shower' },
        { jp:'浴槽', romaji:'yokusō', en:'bathtub' },
        { jp:'トイレ、便器', romaji:'toire, benki', en:'toilet' },
        { jp:'洗面台', romaji:'senmen dai', en:'sink/washbasin' },
        { jp:'スポンジ', romaji:'suponji', en:'sponge' },
        { jp:'洗剤', romaji:'senzai', en:'laundry detergent' },
    ],
    /* Ch 23 */  [
        { jp:'しごと', romaji:'shigoto', en:'job / work' },
        { jp:'かいしゃ', romaji:'kaisha', en:'company' },
        { jp:'どうりょう', romaji:'douryou', en:'colleague' },
        { jp:'じむしょ', romaji:'jimusho', en:'office' },
        { jp:'かいぎ', romaji:'kaigi', en:'meeting' },
        { jp:'きゅうりょう', romaji:'kyuuryou', en:'salary' },
        { jp:'やめます', romaji:'yamemasu', en:'to quit' },
        { jp:'はたらきます', romaji:'hatarakimasu', en:'to work' },
        { jp:'つとめます', romaji:'tsutomemasu', en:'to be employed at' },
        { jp:'いそがしい', romaji:'isogashii', en:'busy' },
        { jp:'たいへん', romaji:'taihen', en:'hard / tough' },
        { jp:'お名前', romaji:'o-namae', en:'your name (formal)' },
        { jp:'名字', romaji:'myōji', en:'surname' },
        { jp:'住所', romaji:'jūsho', en:'address' },
        { jp:'郵便番号', romaji:'yūbin bangō', en:'postal code' },
        { jp:'出生地', romaji:'shusshōchi', en:'place of birth' },
        { jp:'職業', romaji:'shokugyō', en:'occupation' },
        { jp:'既婚', romaji:'kikon', en:'married' },
        { jp:'未婚', romaji:'mikon', en:'single (unmarried)' },
        { jp:'離婚', romaji:'rikon', en:'divorced' },
        { jp:'身分証明書', romaji:'mibun shōmeisho', en:'identity card' },
    ],
    /* Ch 24 */  [
        { jp:'もうすぐ', romaji:'mou sugu', en:'very soon' },
        { jp:'つもり', romaji:'tsumori', en:'intention / plan to' },
        { jp:'よてい', romaji:'yotei', en:'schedule / plan' },
        { jp:'けっこんします', romaji:'kekkon shimasu', en:'to get married' },
        { jp:'そつぎょうします', romaji:'sotsugyou shimasu', en:'to graduate' },
        { jp:'りょこうします', romaji:'ryokou shimasu', en:'to travel' },
        { jp:'ひっこします', romaji:'hikkoshi shimasu', en:'to move (house)' },
        { jp:'やくそく', romaji:'yakusoku', en:'promise / appointment' },
        { jp:'ゆめ', romaji:'yume', en:'dream' },
        { jp:'しょうらい', romaji:'shourai', en:'future' },
        { jp:'ホテル', romaji:'hoteru', en:'hotel' },
        { jp:'パスポート', romaji:'pasupōto', en:'passport' },
        { jp:'ビザ', romaji:'biza', en:'visa' },
        { jp:'乗車券', romaji:'jōsha ken', en:'ticket' },
        { jp:'地図', romaji:'chizu', en:'map' },
        { jp:'空港', romaji:'kūkō', en:'airport' },
        { jp:'出発', romaji:'shuppatsu', en:'departure' },
        { jp:'到着', romaji:'tōchaku', en:'arrival' },
        { jp:'荷物', romaji:'nimotsu', en:'luggage' },
        { jp:'列車', romaji:'ressha', en:'train' },
    ],
    /* Ch 25 */  [
        { jp:'これから', romaji:'korekara', en:'from now on' },
        { jp:'よろしくおねがいします', romaji:'yoroshiku onegai shimasu', en:'I look forward to your continued support' },
        { jp:'おつかれさまでした', romaji:'otsukaresama deshita', en:'thank you for your hard work' },
        { jp:'またあいましょう', romaji:'mata aimashou', en:'let\'s meet again' },
        { jp:'げんきでね', romaji:'genki de ne', en:'take care / stay well' },
        { jp:'わかりました', romaji:'wakarimashita', en:'understood / I see' },
        { jp:'おもいで', romaji:'omoide', en:'memories' },
        { jp:'いちばん', romaji:'ichiban', en:'number one / best' },
        { jp:'たいせつ', romaji:'taisetsu', en:'important / precious' },
        { jp:'がんばります', romaji:'ganbarimasu', en:'I will do my best' },
        { jp:'挨拶する', romaji:'aisatsu suru', en:'to greet' },
        { jp:'元気？', romaji:'genki?', en:'How are you?' },
        { jp:'さようなら', romaji:'sayōnara', en:'goodbye' },
        { jp:'バイバイ', romaji:'baibai', en:'bye (fam.)' },
        { jp:'じゃあね', romaji:'jā ne', en:'see you soon' },
        { jp:'さらば', romaji:'saraba', en:'farewell' },
        { jp:'またね', romaji:'mata ne', en:'so long' },
        { jp:'ありがとう', romaji:'arigatō', en:'thank you' },
        { jp:'どうもありがとう', romaji:'dōmo arigatō', en:'thank you very much' },
        { jp:'失礼', romaji:'shitsurei', en:'excuse me' },
        { jp:'日本', romaji:'nihon', en:'Japan' },
        { jp:'中国', romaji:'chūgoku', en:'China' },
        { jp:'韓国', romaji:'kankoku', en:'South Korea' },
        { jp:'アメリカ', romaji:'america', en:'USA' },
        { jp:'イギリス', romaji:'igirisu', en:'England / UK' },
        { jp:'フランス', romaji:'furansu', en:'France' },
        { jp:'ドイツ', romaji:'doitsu', en:'Germany' },
        { jp:'イタリア', romaji:'itaria', en:'Italy' },
        { jp:'スペイン', romaji:'supein', en:'Spain' },
        { jp:'ロシア', romaji:'roshia', en:'Russia' },
    ],
  ],

  /* ════════ N4 ════════ */
  N4: [
    /* Ch 1 */  [
        { jp:'〜く なります',   romaji:'~ku narimasu',    en:'become ~ (i-adj)' },
        { jp:'〜に なります',   romaji:'~ni narimasu',    en:'become ~ (na-adj / noun)' },
        { jp:'じょうずに',      romaji:'jouzu ni',        en:'skillfully / well' },
        { jp:'べんきょうになります',romaji:'benkyou ni narimasu',en:'study becomes...' },
        { jp:'はやく',          romaji:'hayaku',          en:'quickly / early' },
        { jp:'うまく',          romaji:'umaku',           en:'well / skillfully' },
        { jp:'たいせつ（な）',  romaji:'taisetsu (na)',   en:'important' },
        { jp:'ひつよう（な）',  romaji:'hitsuyou (na)',   en:'necessary' },
        { jp:'むずかしい',      romaji:'muzukashii',      en:'difficult' },
        { jp:'やさしい',        romaji:'yasashii',        en:'easy / kind' },
        { jp:'おもしろい',      romaji:'omoshiroi',       en:'interesting' },
        { jp:'つまらない',      romaji:'tsumaranai',      en:'boring' },
        { jp:'すばらしい',      romaji:'subarashii',      en:'wonderful' },
        { jp:'すごい',          romaji:'sugoi',           en:'amazing' },
    ],
    /* Ch 2 */  [
        { jp:'よめます',        romaji:'yomemasu',        en:'can read' },
        { jp:'かけます',        romaji:'kakemasu',        en:'can write' },
        { jp:'はなせます',      romaji:'hanasemasu',      en:'can speak' },
        { jp:'きけます',        romaji:'kikemasu',        en:'can listen / can hear' },
        { jp:'たべられます',    romaji:'taberaremasu',    en:'can eat' },
        { jp:'のめます',        romaji:'nomemasu',        en:'can drink' },
        { jp:'できます',        romaji:'dekimasu',        en:'can do / able to' },
        { jp:'〜ことが できます',romaji:'~koto ga dekimasu',en:'be able to ~' },
        { jp:'みられます',      romaji:'miraremasu',      en:'can see / can watch' },
        { jp:'〜られます',      romaji:'~raremasu',       en:'potential (ru-verb)' },
        { jp:'〜えます',        romaji:'~emasu',          en:'potential (u-verb)' },
        { jp:'にほんごで',      romaji:'nihongo de',      en:'in Japanese' },
        { jp:'じゆうに',        romaji:'jiyuu ni',        en:'freely / as one pleases' },
    ],
    /* Ch 3 */  [
        { jp:'〜ために',        romaji:'~tame ni',          en:'in order to ~ / for the purpose of ~' },
        { jp:'〜のために',      romaji:'~no tame ni',       en:'for the sake of ~' },
        { jp:'りゆう',          romaji:'riyuu',             en:'reason' },
        { jp:'もくてき',        romaji:'mokuteki',          en:'purpose / aim' },
        { jp:'きっかけ',        romaji:'kikkake',           en:'opportunity / trigger' },
        { jp:'けいけん',        romaji:'keiken',            en:'experience' },
        { jp:'しかく',          romaji:'shikaku',           en:'qualification' },
        { jp:'にゅうがく',      romaji:'nyuugaku',          en:'school admission' },
        { jp:'そつぎょう',      romaji:'sotsugyou',         en:'graduation' },
        { jp:'はいります',      romaji:'hairimasu',         en:'enter / join' },
        { jp:'やとわれます',    romaji:'yatowa remasu',     en:'be employed' },
        { jp:'しゅうしょく',    romaji:'shuushoku',         en:'finding employment' },
        { jp:'しょうらい',      romaji:'shourai',           en:'future' },
        { jp:'ゆめ',            romaji:'yume',              en:'dream' },
    ],
    /* Ch 4 */  [
        { jp:'〜ば',            romaji:'~ba',               en:'if ~ (conditional)' },
        { jp:'〜たら',          romaji:'~tara',             en:'if ~ / once ~ (conditional)' },
        { jp:'〜なら',          romaji:'~nara',             en:'if ~ / in that case' },
        { jp:'もし',            romaji:'moshi',             en:'if (hypothetical)' },
        { jp:'〜のに',          romaji:'~no ni',            en:'although ~ / despite ~' },
        { jp:'〜のに',          romaji:'~no ni',            en:'(purpose) in order to ~' },
        { jp:'きっと',          romaji:'kitto',             en:'certainly / for sure' },
        { jp:'たぶん',          romaji:'tabun',             en:'probably' },
        { jp:'もしかしたら',    romaji:'moshikashitara',    en:'perhaps' },
        { jp:'ぜひ',            romaji:'zehi',              en:'by all means' },
        { jp:'かならず',        romaji:'kanarazu',          en:'without fail / definitely' },
        { jp:'どんなに〜ても',  romaji:'donna ni ~te mo',   en:'no matter how ~' },
    ],
    /* Ch 5 */  [
        { jp:'〜られます',      romaji:'~raremasu',         en:'(passive, ru-verb)' },
        { jp:'〜われます',      romaji:'~waremasu',         en:'(passive, u-verb)' },
        { jp:'〜に よって',     romaji:'~ni yotte',         en:'by ~ (cause/means)' },
        { jp:'〜と いわれています',romaji:'~to iwarete imasu',en:'it is said that ~' },
        { jp:'つかわれます',    romaji:'tsukawaremasu',     en:'be used' },
        { jp:'つくられます',    romaji:'tsukuraremasu',     en:'be made' },
        { jp:'よばれます',      romaji:'yobaremasu',        en:'be called' },
        { jp:'しられています',  romaji:'shirarete imasu',   en:'be known' },
        { jp:'みとめられます',  romaji:'mitomeraremasu',    en:'be recognized / accepted' },
        { jp:'かんがえられます',romaji:'kangaeraremasu',    en:'be considered' },
        { jp:'〜として',        romaji:'~to shite',         en:'as ~ / in the capacity of ~' },
        { jp:'〜によると',      romaji:'~ni yoru to',       en:'according to ~' },
    ],
    /* Ch 6 */  [
        { jp:'〜させます',      romaji:'~sasemasu',         en:'make/let someone do ~ (causative)' },
        { jp:'〜させてください',romaji:'~sasete kudasai',   en:'please let me ~' },
        { jp:'させられます',    romaji:'saseraremasu',      en:'be made to do ~ (causative-passive)' },
        { jp:'はたらかせます',  romaji:'hatarakasemasu',    en:'make (s.o.) work' },
        { jp:'かんがえさせます',romaji:'kangaesasemasu',    en:'make (s.o.) think' },
        { jp:'いわせます',      romaji:'iwasemasu',         en:'make (s.o.) say' },
        { jp:'みせます',        romaji:'misemasu',          en:'show' },
        { jp:'きかせます',      romaji:'kikasemasu',        en:'let (s.o.) hear' },
        { jp:'たべさせます',    romaji:'tabesasemasu',      en:'make/let (s.o.) eat' },
        { jp:'〜てもらいます',  romaji:'~te moraimasu',     en:'have (s.o.) do ~' },
        { jp:'じゆうに',        romaji:'jiyuu ni',          en:'freely' },
    ],
    /* Ch 7 */  [
        { jp:'〜ば よかった',   romaji:'~ba yokatta',       en:'I should have ~ / I wish I had ~' },
        { jp:'〜なければ よかった',romaji:'~nakereba yokatta',en:'I shouldn\'t have ~' },
        { jp:'こうかい',        romaji:'koukai',            en:'regret' },
        { jp:'ざんねん（な）',  romaji:'zannen (na)',        en:'unfortunate / disappointing' },
        { jp:'しっぱい',        romaji:'shippai',           en:'failure / mistake' },
        { jp:'まちがい',        romaji:'machigai',          en:'mistake' },
        { jp:'きをつけます',    romaji:'ki o tsukemasu',    en:'be careful' },
        { jp:'〜てしまいます',  romaji:'~te shimaimasu',    en:'end up doing ~ / (regrettably) did ~' },
        { jp:'つい',            romaji:'tsui',              en:'unintentionally / by habit' },
        { jp:'うっかり',        romaji:'ukkari',            en:'carelessly' },
        { jp:'なんで',          romaji:'nande',             en:'why (casual)' },
    ],
    /* Ch 8 */  [
        { jp:'〜て あげます',   romaji:'~te agemasu',       en:'do ~ for s.o. (outward)' },
        { jp:'〜て もらいます', romaji:'~te moraimasu',     en:'have s.o. do ~ for me' },
        { jp:'〜て くれます',   romaji:'~te kuremasu',      en:'s.o. does ~ for me' },
        { jp:'てつだいます',    romaji:'tetsudaimasu',      en:'help' },
        { jp:'せわを します',   romaji:'sewa o shimasu',    en:'take care of' },
        { jp:'おみまい',        romaji:'omimai',            en:'get-well visit' },
        { jp:'おれい',          romaji:'orei',              en:'thank-you gift / gratitude' },
        { jp:'あいさつ',        romaji:'aisatsu',           en:'greeting' },
        { jp:'かしこまりました',romaji:'kashikomarimashita',en:'Certainly. / Understood. (formal)' },
        { jp:'おきのどくに',    romaji:'oki no doku ni',    en:'I\'m sorry to hear that' },
        { jp:'よろこんで',      romaji:'yorokonde',         en:'with pleasure / gladly' },
    ],
    /* Ch 9 */  [
        { jp:'〜たら どうですか',romaji:'~tara dou desu ka',en:'How about doing ~? / Why don\'t you ~?' },
        { jp:'〜ほうがいいです',romaji:'~hou ga ii desu',   en:'It\'s better to ~ / You should ~' },
        { jp:'〜ないほうがいい',romaji:'~nai hou ga ii',    en:'better not to ~' },
        { jp:'かならず',        romaji:'kanarazu',          en:'definitely' },
        { jp:'きをつけて',      romaji:'ki o tsukete',      en:'take care / be careful' },
        { jp:'しんぱいします',  romaji:'shinpai shimasu',   en:'worry' },
        { jp:'こまります',      romaji:'komarimasu',        en:'be troubled / in a bind' },
        { jp:'そうだん',        romaji:'soudan',            en:'consultation / advice' },
        { jp:'そうだんします',  romaji:'soudan shimasu',    en:'consult / seek advice' },
        { jp:'いけん',          romaji:'iken',              en:'opinion' },
        { jp:'ていあん',        romaji:'teian',             en:'suggestion / proposal' },
    ],
    /* Ch 10 */  [
        { jp:'〜たら、すぐ',    romaji:'~tara, sugu',       en:'as soon as ~ / right after ~' },
        { jp:'すぐ',            romaji:'sugu',              en:'immediately / soon' },
        { jp:'やっと',          romaji:'yatto',             en:'finally / at last' },
        { jp:'とうとう',        romaji:'toutou',            en:'at last / in the end' },
        { jp:'けっきょく',      romaji:'kekkyoku',          en:'in the end / eventually' },
        { jp:'ところで',        romaji:'tokoro de',         en:'by the way' },
        { jp:'それで',          romaji:'sorede',            en:'so / therefore' },
        { jp:'それに',          romaji:'soreni',            en:'moreover / besides' },
        { jp:'しかも',          romaji:'shikamo',           en:'moreover / in addition' },
        { jp:'ところが',        romaji:'tokoroga',          en:'however / but (unexpected)' },
        { jp:'なにしろ',        romaji:'nani shiro',        en:'at any rate / above all' },
    ],
    /* Ch 11 */  [
        { jp:'〜てみます',      romaji:'~te mimasu',        en:'try doing ~' },
        { jp:'〜てみましょう',  romaji:'~te mimashou',      en:'let\'s try doing ~' },
        { jp:'やってみます',    romaji:'yatte mimasu',      en:'try doing it / give it a go' },
        { jp:'たべてみます',    romaji:'tabete mimasu',     en:'try eating' },
        { jp:'きいてみます',    romaji:'kiite mimasu',      en:'try asking / try listening' },
        { jp:'さがします',      romaji:'sagashimasu',       en:'look for / search' },
        { jp:'しらべます',      romaji:'shirabemasu',       en:'investigate / look up' },
        { jp:'たしかめます',    romaji:'tashikamemasu',     en:'confirm / verify' },
        { jp:'みつけます',      romaji:'mitsukemasu',       en:'find' },
        { jp:'うまくいきます',  romaji:'umaku ikimasu',     en:'go well / succeed' },
        { jp:'むずかしい',      romaji:'muzukashii',        en:'difficult' },
        { jp:'むり（な）',      romaji:'muri (na)',         en:'impossible / unreasonable' },
    ],
    /* Ch 12 */  [
        { jp:'〜ておきます',    romaji:'~te okimasu',       en:'do ~ in advance / do ~ for later' },
        { jp:'じゅんびして おきます',romaji:'junbi shite okimasu',en:'prepare in advance' },
        { jp:'よやくして おきます',romaji:'yoyaku shite okimasu',en:'book in advance' },
        { jp:'かいぎ',          romaji:'kaigi',             en:'meeting / conference' },
        { jp:'よこく',          romaji:'yokoku',            en:'advance notice' },
        { jp:'あらかじめ',      romaji:'arakajime',         en:'in advance / beforehand' },
        { jp:'したく',          romaji:'shitaku',           en:'preparation / getting ready' },
        { jp:'てはいを します', romaji:'tehai o shimasu',   en:'make arrangements' },
        { jp:'かくにん',        romaji:'kakunin',           en:'confirmation / check' },
        { jp:'かくにんします',  romaji:'kakunin shimasu',   en:'confirm / check' },
        { jp:'よしゅう',        romaji:'yoshuu',            en:'preview study / preparation' },
        { jp:'ふくしゅう',      romaji:'fukushuu',          en:'review study' },
    ],
    /* Ch 13 */  [
        { jp:'〜ている ひと',   romaji:'~te iru hito',      en:'person who is ~ing' },
        { jp:'〜た もの',       romaji:'~ta mono',          en:'thing that was ~ed' },
        { jp:'〜という〜',      romaji:'~to iu ~',          en:'~ called ~ / ~ that says ~' },
        { jp:'〜ところ',        romaji:'~tokoro',           en:'place where ~ / just about to ~' },
        { jp:'〜とき',          romaji:'~toki',             en:'when ~ / at the time of ~' },
        { jp:'〜まで',          romaji:'~made',             en:'until ~ / as far as ~' },
        { jp:'〜あいだ（に）',  romaji:'~aida (ni)',        en:'while ~ / during ~' },
        { jp:'〜うちに',        romaji:'~uchi ni',          en:'while ~ / before it\'s too late' },
        { jp:'〜かぎり',        romaji:'~kagiri',           en:'as long as ~ / as far as ~' },
        { jp:'〜まま',          romaji:'~mama',             en:'as ~ / leaving ~ as it is' },
    ],
    /* Ch 14 */  [
        { jp:'〜ので',          romaji:'~node',             en:'because ~ (reason, polite)' },
        { jp:'〜のに',          romaji:'~no ni',            en:'despite ~ / even though ~' },
        { jp:'〜けれど（も）',  romaji:'~keredo(mo)',        en:'although ~ / but ~' },
        { jp:'〜が',            romaji:'~ga',               en:'but ~ / however ~' },
        { jp:'〜ながら',        romaji:'~nagara',           en:'while doing ~ (simultaneous)' },
        { jp:'〜し、〜し',      romaji:'~shi, ~shi',        en:'both ~ and ~ / what\'s more' },
        { jp:'〜て（から）',    romaji:'~te (kara)',        en:'after doing ~' },
        { jp:'〜まま',          romaji:'~mama',             en:'leaving ~ as is' },
        { jp:'〜とたん（に）',  romaji:'~totan (ni)',        en:'as soon as / the moment ~' },
        { jp:'ちょうど',        romaji:'choudo',            en:'exactly / just' },
        { jp:'ようやく',        romaji:'youyaku',           en:'finally / at last' },
    ],
    /* Ch 15 */  [
        { jp:'けんこう',        romaji:'kenkou',            en:'health' },
        { jp:'たいちょう',      romaji:'taichou',           en:'physical condition' },
        { jp:'ちょうし',        romaji:'choushi',           en:'condition / tune' },
        { jp:'うんどう',        romaji:'undou',             en:'exercise' },
        { jp:'ダイエット',      romaji:'daietto',           en:'diet' },
        { jp:'ていき けんしん', romaji:'teiki kenshin',     en:'regular health check' },
        { jp:'えいよう',        romaji:'eiyou',             en:'nutrition' },
        { jp:'すいみん',        romaji:'suimin',            en:'sleep' },
        { jp:'ストレス',        romaji:'sutoresu',          en:'stress' },
        { jp:'きゅうけい',      romaji:'kyuukei',           en:'rest / break' },
        { jp:'さんぽ',          romaji:'sanpo',             en:'walk / stroll' },
        { jp:'ヨガ',            romaji:'yoga',              en:'yoga' },
        { jp:'はしります',      romaji:'hashirimasu',       en:'run' },
        { jp:'およぎます',      romaji:'oyogimasu',         en:'swim' },
    ],
    /* Ch 16 */  [
        { jp:'しごと',          romaji:'shigoto',           en:'work / job' },
        { jp:'きんむ',          romaji:'kinmu',             en:'duty / service' },
        { jp:'どうりょう',      romaji:'douryou',           en:'colleague' },
        { jp:'じょうし',        romaji:'joushi',            en:'superior / boss' },
        { jp:'ぶか',            romaji:'buka',              en:'subordinate' },
        { jp:'かかりちょう',    romaji:'kakarichou',        en:'section chief' },
        { jp:'かちょう',        romaji:'kachou',            en:'section manager' },
        { jp:'しゃちょう',      romaji:'shachou',           en:'company president' },
        { jp:'きゅうりょう',    romaji:'kyuuryou',          en:'salary' },
        { jp:'ざんぎょう',      romaji:'zangyou',           en:'overtime' },
        { jp:'きゅうか',        romaji:'kyuuka',            en:'paid holiday' },
        { jp:'てんきん',        romaji:'tenkin',            en:'job transfer' },
        { jp:'しょうしん',      romaji:'shoushin',          en:'promotion' },
        { jp:'たいしょく',      romaji:'taishoku',          en:'retirement' },
    ],
    /* Ch 17 */  [
        { jp:'〜ながら',        romaji:'~nagara',           en:'while doing ~ (same time)' },
        { jp:'〜あいだ',        romaji:'~aida',             en:'while / during' },
        { jp:'〜とき',          romaji:'~toki',             en:'when / at the time of' },
        { jp:'テレビ',          romaji:'terebi',            en:'television' },
        { jp:'ラジオ',          romaji:'rajio',             en:'radio' },
        { jp:'おんがく',        romaji:'ongaku',            en:'music' },
        { jp:'うた',            romaji:'uta',               en:'song' },
        { jp:'うたいます',      romaji:'utaimasu',          en:'sing' },
        { jp:'おどります',      romaji:'odorimasu',         en:'dance' },
        { jp:'さんぽします',    romaji:'sanpo shimasu',     en:'take a walk' },
        { jp:'かんがえます',    romaji:'kangaemasu',        en:'think' },
        { jp:'ひとりごと',      romaji:'hitorigoto',        en:'talking to oneself' },
    ],
    /* Ch 18 */  [
        { jp:'せんもん',        romaji:'senmon',            en:'specialisation / major' },
        { jp:'けんきゅう',      romaji:'kenkyuu',           en:'research' },
        { jp:'ろんぶん',        romaji:'ronbun',            en:'thesis / paper' },
        { jp:'じっけん',        romaji:'jikken',            en:'experiment' },
        { jp:'ぶんがく',        romaji:'bungaku',           en:'literature' },
        { jp:'けいざい',        romaji:'keizai',            en:'economics' },
        { jp:'ほうりつ',        romaji:'houritsu',          en:'law' },
        { jp:'こうがく',        romaji:'kougaku',           en:'engineering' },
        { jp:'いがく',          romaji:'igaku',             en:'medicine (study)' },
        { jp:'しんりがく',      romaji:'shinrigaku',        en:'psychology' },
        { jp:'れきし',          romaji:'rekishi',           en:'history' },
        { jp:'てつがく',        romaji:'tetsugaku',         en:'philosophy' },
        { jp:'そつぎょう',      romaji:'sotsugyou',         en:'graduation' },
        { jp:'にゅうがく',      romaji:'nyuugaku',          en:'admission (to school)' },
    ],
    /* Ch 19 */  [
        { jp:'ぶんか',          romaji:'bunka',             en:'culture' },
        { jp:'でんとう',        romaji:'dentou',            en:'tradition' },
        { jp:'まつり',          romaji:'matsuri',           en:'festival' },
        { jp:'しきたり',        romaji:'shikitari',         en:'custom / convention' },
        { jp:'れいぎ',          romaji:'reigi',             en:'manners / etiquette' },
        { jp:'おじぎ',          romaji:'ojigi',             en:'bow' },
        { jp:'きもの',          romaji:'kimono',            en:'kimono' },
        { jp:'ゆかた',          romaji:'yukata',            en:'summer yukata' },
        { jp:'おちゃ',          romaji:'ocha',              en:'tea ceremony / tea' },
        { jp:'いけばな',        romaji:'ikebana',           en:'flower arrangement' },
        { jp:'しょどう',        romaji:'shodou',            en:'calligraphy' },
        { jp:'にほんしょく',    romaji:'nihonshoku',        en:'Japanese food' },
        { jp:'うきよえ',        romaji:'ukiyoe',            en:'ukiyo-e woodblock print' },
        { jp:'かぶき',          romaji:'kabuki',            en:'kabuki theatre' },
    ],
    /* Ch 20 */  [
        { jp:'かんきょう',      romaji:'kankyou',           en:'environment' },
        { jp:'おせん',          romaji:'osen',              en:'pollution' },
        { jp:'たいきおせん',    romaji:'taiki osen',        en:'air pollution' },
        { jp:'みずおせん',      romaji:'mizu osen',         en:'water pollution' },
        { jp:'おんだんか',      romaji:'ondanka',           en:'global warming' },
        { jp:'ちきゅう',        romaji:'chikyuu',           en:'earth / globe' },
        { jp:'リサイクル',      romaji:'risaikuru',         en:'recycling' },
        { jp:'エネルギー',      romaji:'enerugii',          en:'energy' },
        { jp:'たいよう',        romaji:'taiyou',            en:'sun' },
        { jp:'しぜん',          romaji:'shizen',            en:'nature' },
        { jp:'もんだい',        romaji:'mondai',            en:'problem / issue' },
        { jp:'かいけつ',        romaji:'kaiketsu',          en:'solution / resolution' },
        { jp:'とりくみます',    romaji:'torikumimasu',      en:'tackle / work on' },
    ],
    /* Ch 21 */  [
        { jp:'あやまります',    romaji:'ayamarimasu',       en:'apologize' },
        { jp:'なかなおりします',romaji:'nakanaorimasu',     en:'make up (after a fight)' },
        { jp:'けんかします',    romaji:'kenka shimasu',     en:'quarrel / fight' },
        { jp:'ゆるします',      romaji:'yurushimasu',       en:'forgive / permit' },
        { jp:'しつれい',        romaji:'shitsurei',         en:'rudeness / impoliteness' },
        { jp:'もうしわけ',      romaji:'moushiwake',        en:'excuse / apology' },
        { jp:'こころから',      romaji:'kokoro kara',       en:'from the heart / sincerely' },
        { jp:'しんけんに',      romaji:'shinken ni',        en:'seriously' },
        { jp:'きちんと',        romaji:'kichinto',          en:'properly / neatly' },
        { jp:'ちゃんと',        romaji:'chanto',            en:'properly / correctly' },
        { jp:'すなおに',        romaji:'sunao ni',          en:'honestly / obediently' },
    ],
    /* Ch 22 */  [
        { jp:'ニュース',        romaji:'nyuusu',            en:'news' },
        { jp:'じけん',          romaji:'jiken',             en:'incident / case' },
        { jp:'じこ',            romaji:'jiko',              en:'accident' },
        { jp:'じしん',          romaji:'jishin',            en:'earthquake' },
        { jp:'たいふう',        romaji:'taifuu',            en:'typhoon' },
        { jp:'こうずい',        romaji:'kouzui',            en:'flood' },
        { jp:'じんこう',        romaji:'jinkou',            en:'population' },
        { jp:'けいざい',        romaji:'keizai',            en:'economy' },
        { jp:'せいじ',          romaji:'seiji',             en:'politics' },
        { jp:'しゃかい',        romaji:'shakai',            en:'society' },
        { jp:'こくさい',        romaji:'kokusai',           en:'international' },
        { jp:'しんぶんしゃ',    romaji:'shimbunsha',        en:'newspaper company' },
        { jp:'レポーター',      romaji:'repootaa',          en:'reporter' },
        { jp:'ほうどう',        romaji:'houdou',            en:'news report' },
    ],
    /* Ch 23 */  [
        { jp:'てきとう（な）',  romaji:'tekitou (na)',       en:'appropriate / halfhearted' },
        { jp:'まじめ（な）',    romaji:'majime (na)',        en:'serious / earnest' },
        { jp:'いいかげん（な）',romaji:'iikagen (na)',       en:'irresponsible / halfhearted' },
        { jp:'ていねい（な）',  romaji:'teinei (na)',        en:'polite / careful' },
        { jp:'らんぼう（な）',  romaji:'ranbou (na)',        en:'rough / violent' },
        { jp:'しんせつ（な）',  romaji:'shinsetsu (na)',     en:'kind / helpful' },
        { jp:'むじゃき（な）',  romaji:'mujaki (na)',        en:'innocent / carefree' },
        { jp:'なまけます',      romaji:'namakemasu',        en:'be lazy' },
        { jp:'がんばります',    romaji:'ganbarimasu',       en:'do one\'s best' },
        { jp:'どりょく',        romaji:'doryoku',           en:'effort' },
        { jp:'こんき',          romaji:'konki',             en:'patience / perseverance' },
        { jp:'つとめます',      romaji:'tsutomemasu',       en:'make an effort / work' },
    ],
    /* Ch 24 */  [
        { jp:'つたえます',      romaji:'tsutaemasu',        en:'convey / communicate' },
        { jp:'つたわります',    romaji:'tsutawarimasu',     en:'be conveyed / reach' },
        { jp:'りかいします',    romaji:'rikai shimasu',     en:'understand' },
        { jp:'ごかい',          romaji:'gokai',             en:'misunderstanding' },
        { jp:'ごかいします',    romaji:'gokai shimasu',     en:'misunderstand' },
        { jp:'たしかめます',    romaji:'tashikamemasu',     en:'confirm / make sure' },
        { jp:'はっきり',        romaji:'hakkiri',           en:'clearly' },
        { jp:'ていねいに',      romaji:'teinei ni',         en:'politely / carefully' },
        { jp:'かんたんに',      romaji:'kantan ni',         en:'simply / easily' },
        { jp:'くわしく',        romaji:'kuwashiku',         en:'in detail' },
        { jp:'みじかく',        romaji:'mijikaku',          en:'briefly' },
        { jp:'ことば',          romaji:'kotoba',            en:'word / language' },
        { jp:'ひょうげん',      romaji:'hyougen',           en:'expression' },
    ],
    /* Ch 25 */  [
        { jp:'おせわに なりました',romaji:'osewa ni narimashita',en:'Thank you for your help (past)' },
        { jp:'おかげさまで',    romaji:'okagesama de',      en:'thanks to you' },
        { jp:'たいへん おせわに なりました',romaji:'taihen osewa ni narimashita',en:'I\'ve been in your debt greatly' },
        { jp:'これからも どうぞ よろしく',romaji:'korekara mo douzo yoroshiku',en:'Please continue to look after me' },
        { jp:'またいつか',      romaji:'mata itsuka',       en:'sometime again' },
        { jp:'おたがいに',      romaji:'otagai ni',         en:'each other / mutually' },
        { jp:'たいせつにします',romaji:'taisetsu ni shimasu',en:'will treasure / will take care' },
        { jp:'わすれません',    romaji:'wasuremasen',       en:'will not forget' },
        { jp:'おもいで',        romaji:'omoide',            en:'memory / recollection' },
        { jp:'かんしゃ',        romaji:'kansha',            en:'gratitude / appreciation' },
        { jp:'えがお',          romaji:'egao',              en:'smiling face' },
        { jp:'さいかい',        romaji:'saikai',            en:'reunion' },
        { jp:'またあう',        romaji:'mata au',           en:'meet again' },
    ],
  ],

  /* ════════ N3 ════════ */
  N3: [
    /* Ch 1 */  [
        { jp:'かわります',      romaji:'kawarimasu',        en:'change / differ' },
        { jp:'きづきます',      romaji:'kizukimasu',        en:'notice / become aware' },
        { jp:'おどろきます',    romaji:'odorokimasu',       en:'be surprised' },
        { jp:'ふしぎ（な）',    romaji:'fushigi (na)',       en:'strange / mysterious / wonderful' },
        { jp:'きかい',          romaji:'kikai',             en:'opportunity / chance' },
        { jp:'じょうきょう',    romaji:'joukyou',           en:'situation / circumstances' },
        { jp:'じじょう',        romaji:'jijou',             en:'circumstances / reason' },
        { jp:'けいか',          romaji:'keika',             en:'progress / passage (of time)' },
        { jp:'てん',            romaji:'ten',               en:'point / aspect' },
        { jp:'ようす',          romaji:'yousu',             en:'appearance / situation / manner' },
        { jp:'〜らしい',        romaji:'~rashii',           en:'seems like ~ / apparently' },
        { jp:'〜ようだ',        romaji:'~you da',           en:'appears to be ~' },
        { jp:'〜みたいだ',      romaji:'~mitai da',         en:'looks like ~ / seems like ~' },
    ],
    /* Ch 2 */  [
        { jp:'たのみます',      romaji:'tanomimasu',        en:'request / ask a favour' },
        { jp:'おねがいします',  romaji:'onegai shimasu',    en:'please (I request)' },
        { jp:'〜ていただけますか',romaji:'~te itadakemasu ka',en:'Would you please ~?' },
        { jp:'〜てくださいませんか',romaji:'~te kudasaimasen ka',en:'Won\'t you please ~?' },
        { jp:'もしよければ',    romaji:'moshi yokereba',    en:'if you don\'t mind' },
        { jp:'ご迷惑を おかけして',romaji:'gomeiwaku o okake shite',en:'causing you trouble' },
        { jp:'こころよく',      romaji:'kokoroyoku',        en:'willingly / cheerfully' },
        { jp:'むり（な）',      romaji:'muri (na)',         en:'impossible / unreasonable' },
        { jp:'えんりょ',        romaji:'enryo',             en:'reserve / restraint / hesitation' },
        { jp:'えんりょします',  romaji:'enryo shimasu',     en:'hold back / hesitate' },
        { jp:'さしつかえない',  romaji:'sashitsukaenai',    en:'no objection / all right' },
        { jp:'かしこまりました',romaji:'kashikomarimashita',en:'Certainly. (very formal)' },
    ],
    /* Ch 3 */  [
        { jp:'じかん',          romaji:'jikan',             en:'time' },
        { jp:'かんり',          romaji:'kanri',             en:'management / control' },
        { jp:'ゆうこうに',      romaji:'yuukou ni',         en:'effectively / usefully' },
        { jp:'むだ（な）',      romaji:'muda (na)',         en:'wasteful / pointless' },
        { jp:'わりあい',        romaji:'wariai',            en:'proportion / comparatively' },
        { jp:'わりに',          romaji:'wari ni',           en:'comparatively / for ~' },
        { jp:'〜わりには',      romaji:'~wari ni wa',       en:'for ~ (unexpectedly)' },
        { jp:'きげん',          romaji:'kigen',             en:'deadline / expiry' },
        { jp:'しめきり',        romaji:'shimekiri',         en:'deadline / closing time' },
        { jp:'まにあいます',    romaji:'ma ni aimasu',      en:'be in time / make it' },
        { jp:'おくれます',      romaji:'okuremasu',         en:'be late / delayed' },
        { jp:'あまります',      romaji:'amarimasu',         en:'remain / be left over' },
        { jp:'〜うちに',        romaji:'~uchi ni',          en:'while ~ / before ~' },
    ],
    /* Ch 4 */  [
        { jp:'かします',        romaji:'kashimasu',         en:'lend' },
        { jp:'かります',        romaji:'karimasu',          en:'borrow' },
        { jp:'つかいます',      romaji:'tsukaimasu',        en:'use' },
        { jp:'かえします',      romaji:'kaeshimasu',        en:'return (something)' },
        { jp:'なくします',      romaji:'nakushimasu',       en:'lose' },
        { jp:'こわします',      romaji:'kowashimasu',       en:'break / destroy' },
        { jp:'こわれます',      romaji:'kowaremasu',        en:'break / be broken' },
        { jp:'しゅうり',        romaji:'shuuri',            en:'repair' },
        { jp:'しゅうりします',  romaji:'shuuri shimasu',    en:'repair' },
        { jp:'そっくり',        romaji:'sokkuri',           en:'exactly / as is' },
        { jp:'そのまま',        romaji:'sono mama',         en:'as it is / unchanged' },
        { jp:'べつに',          romaji:'betsu ni',          en:'separately / not particularly' },
        { jp:'くわしい',        romaji:'kuwashii',          en:'detailed / knowledgeable' },
    ],
    /* Ch 5 */  [
        { jp:'ことわります',    romaji:'kotowarimasu',      en:'decline / refuse' },
        { jp:'えんりょします',  romaji:'enryo shimasu',     en:'refrain / hold back' },
        { jp:'じつは',          romaji:'jitsu wa',          en:'actually / to tell the truth' },
        { jp:'あいにく',        romaji:'ainiku',            en:'unfortunately / unluckily' },
        { jp:'せっかくですが',  romaji:'sekkaku desu ga',   en:'I appreciate the offer, but...' },
        { jp:'おさしつかえなければ',romaji:'osashitsukae nakereba',en:'if it\'s not too much trouble' },
        { jp:'つごうが わるい', romaji:'tsugou ga warui',   en:'inconvenient / bad timing' },
        { jp:'さしつかえます',  romaji:'sashitsukaeimasu',  en:'be inconvenient / have an objection' },
        { jp:'むりです',        romaji:'muri desu',         en:'it\'s impossible' },
        { jp:'きびしい',        romaji:'kibishii',          en:'strict / harsh / severe' },
        { jp:'やむをえない',    romaji:'yamu o enai',       en:'unavoidable / no choice' },
    ],
    /* Ch 6 */  [
        { jp:'かんじょう',      romaji:'kanjou',            en:'emotion / feeling' },
        { jp:'よろこびます',    romaji:'yorokobimasu',      en:'be pleased / rejoice' },
        { jp:'かなしみます',    romaji:'kanashimimasu',     en:'feel sad' },
        { jp:'おこります',      romaji:'okorimasu',         en:'get angry' },
        { jp:'こわがります',    romaji:'kowagarimasu',      en:'be afraid' },
        { jp:'はずかしい',      romaji:'hazukashii',        en:'embarrassed / ashamed' },
        { jp:'さびしい',        romaji:'sabishii',          en:'lonely' },
        { jp:'うれしい',        romaji:'ureshii',           en:'happy / glad' },
        { jp:'かなしい',        romaji:'kanashii',          en:'sad' },
        { jp:'つらい',          romaji:'tsurai',            en:'painful / hard' },
        { jp:'たのしい',        romaji:'tanoshii',          en:'fun / enjoyable' },
        { jp:'こうふん',        romaji:'koufun',            en:'excitement' },
        { jp:'あんしん',        romaji:'anshin',            en:'relief / ease of mind' },
        { jp:'ふあん（な）',    romaji:'fuan (na)',         en:'anxiety / unease' },
    ],
    /* Ch 7 */  [
        { jp:'いけん',          romaji:'iken',              en:'opinion' },
        { jp:'しゅちょう',      romaji:'shuchou',           en:'assertion / claim' },
        { jp:'りゆう',          romaji:'riyuu',             en:'reason' },
        { jp:'こんきょ',        romaji:'konkyo',            en:'grounds / basis' },
        { jp:'さんせい',        romaji:'sansei',            en:'agreement' },
        { jp:'さんせいします',  romaji:'sansei shimasu',    en:'agree' },
        { jp:'はんたい',        romaji:'hantai',            en:'opposition' },
        { jp:'はんたいします',  romaji:'hantai shimasu',    en:'oppose' },
        { jp:'なっとく',        romaji:'nattoku',           en:'understanding / consent' },
        { jp:'なっとくします',  romaji:'nattoku shimasu',   en:'be convinced / agree' },
        { jp:'ぎろん',          romaji:'giron',             en:'argument / discussion' },
        { jp:'とうろん',        romaji:'touron',            en:'debate' },
        { jp:'〜にもかかわらず',romaji:'~ni mo kakawarazu', en:'despite ~ / in spite of ~' },
        { jp:'〜にしたがって',  romaji:'~ni shitagatte',    en:'as ~ / in accordance with ~' },
    ],
    /* Ch 8 */  [
        { jp:'〜といっていました',romaji:'~to itte imashita',en:'was saying that ~' },
        { jp:'〜とのことです',  romaji:'~to no koto desu',  en:'I hear that ~' },
        { jp:'〜によると',      romaji:'~ni yoru to',       en:'according to ~' },
        { jp:'〜そうです',      romaji:'~sou desu',         en:'I heard that ~' },
        { jp:'つたえます',      romaji:'tsutaemasu',        en:'convey / pass on' },
        { jp:'つたわります',    romaji:'tsutawarimasu',     en:'be conveyed / reach' },
        { jp:'ほうこく',        romaji:'houkoku',           en:'report' },
        { jp:'ほうこくします',  romaji:'houkoku shimasu',   en:'report / inform' },
        { jp:'れんらく',        romaji:'renraku',           en:'contact / communication' },
        { jp:'しらせます',      romaji:'shirasemasu',       en:'inform / notify' },
        { jp:'つたえてください',romaji:'tsutaete kudasai',  en:'please tell (s.o.)' },
        { jp:'おつたえします',  romaji:'otsutae shimasu',   en:'I will convey (humble)' },
    ],
    /* Ch 9 */  [
        { jp:'ぶんかてき（な）',romaji:'bunkanteki (na)',    en:'cultural' },
        { jp:'しゅうかん',      romaji:'shuukan',           en:'habit / custom' },
        { jp:'かんしゅう',      romaji:'kanshuu',           en:'custom / convention' },
        { jp:'タブー',          romaji:'tabuu',             en:'taboo' },
        { jp:'ちがい',          romaji:'chigai',            en:'difference' },
        { jp:'きょうつう（な）',romaji:'kyoutsuu (na)',      en:'common / shared' },
        { jp:'こうてい',        romaji:'koutei',            en:'affirmation / positive' },
        { jp:'ひてい',          romaji:'hitei',             en:'negation / denial' },
        { jp:'そんちょう',      romaji:'sonchou',           en:'respect' },
        { jp:'そんちょうします',romaji:'sonchou shimasu',   en:'respect' },
        { jp:'りかい',          romaji:'rikai',             en:'understanding' },
        { jp:'うけいれます',    romaji:'ukeiremasu',        en:'accept / receive' },
        { jp:'てきおう',        romaji:'tekiou',            en:'adaptation' },
        { jp:'てきおうします',  romaji:'tekiou shimasu',    en:'adapt / adjust' },
    ],
    /* Ch 10 */  [
        { jp:'しぜん',          romaji:'shizen',            en:'nature' },
        { jp:'かんきょう',      romaji:'kankyou',           en:'environment' },
        { jp:'せいたい',        romaji:'seitai',            en:'ecosystem' },
        { jp:'タイキ',          romaji:'taiki',             en:'atmosphere / air' },
        { jp:'きこう',          romaji:'kikou',             en:'climate' },
        { jp:'きしょう',        romaji:'kishou',            en:'weather / climate' },
        { jp:'きせつ',          romaji:'kisetsu',           en:'season' },
        { jp:'あたたかい',      romaji:'atatakai',          en:'warm' },
        { jp:'すずしい',        romaji:'suzushii',          en:'cool' },
        { jp:'さむい',          romaji:'samui',             en:'cold' },
        { jp:'おんだんか',      romaji:'ondanka',           en:'global warming' },
        { jp:'ていたんそ',      romaji:'teitanso',          en:'low carbon' },
        { jp:'さいがい',        romaji:'saigai',            en:'disaster' },
        { jp:'ひなん',          romaji:'hinan',             en:'evacuation' },
        { jp:'ひなんします',    romaji:'hinan shimasu',     en:'evacuate' },
    ],
    /* Ch 11 */  [
        { jp:'みだし',          romaji:'midashi',           en:'headline' },
        { jp:'きじ',            romaji:'kiji',              en:'article' },
        { jp:'しゃせつ',        romaji:'shasetsu',          en:'editorial' },
        { jp:'とくしゅう',      romaji:'tokushuu',          en:'special feature' },
        { jp:'ちょうさ',        romaji:'chousa',            en:'survey / research / investigation' },
        { jp:'けっか',          romaji:'kekka',             en:'result / outcome' },
        { jp:'えいきょう',      romaji:'eikyou',            en:'influence / effect' },
        { jp:'たいさく',        romaji:'taisaku',           en:'countermeasure' },
        { jp:'げんいん',        romaji:'genin',             en:'cause' },
        { jp:'かいぜん',        romaji:'kaizen',            en:'improvement' },
        { jp:'かいぜんします',  romaji:'kaizen shimasu',    en:'improve' },
        { jp:'こうか',          romaji:'kouka',             en:'effect / result' },
        { jp:'すいしん',        romaji:'suishin',           en:'promotion / drive' },
        { jp:'もくひょう',      romaji:'mokuhyou',          en:'goal / objective' },
    ],
    /* Ch 12 */  [
        { jp:'〜にもかかわらず',romaji:'~ni mo kakawarazu', en:'despite ~ / in spite of ~' },
        { jp:'〜さえ〜ば',      romaji:'~sae ~ba',          en:'if only ~ then ~' },
        { jp:'〜にすぎない',    romaji:'~ni suginai',       en:'nothing but ~ / merely ~' },
        { jp:'〜にちがいない',  romaji:'~ni chigainai',     en:'must be ~ / no doubt' },
        { jp:'〜はずだ',        romaji:'~hazu da',          en:'expected to be ~ / should be ~' },
        { jp:'〜はずがない',    romaji:'~hazu ga nai',      en:'there\'s no way ~' },
        { jp:'〜べきだ',        romaji:'~beki da',          en:'should ~ / ought to ~' },
        { jp:'〜べきではない',  romaji:'~beki de wa nai',   en:'shouldn\'t ~ / ought not to ~' },
        { jp:'〜に反して',      romaji:'~ni hanshite',      en:'contrary to ~' },
        { jp:'〜にともなって',  romaji:'~ni tomonatte',     en:'along with ~ / in accordance with ~' },
        { jp:'〜をもとに',      romaji:'~wo moto ni',       en:'based on ~ / drawing from ~' },
        { jp:'〜において',      romaji:'~ni oite',          en:'in ~ / at ~ (formal)' },
        { jp:'〜に関して',      romaji:'~ni kanshite',      en:'regarding ~ / concerning ~' },
        { jp:'〜にとって',      romaji:'~ni totte',         en:'for ~ / to ~ (from the perspective of)' },
    ],
  ],

  /* ════════ N2 ════════ */
  N2: [
    /* Ch 1 */  [
        { jp:'かえって',        romaji:'kaette',            en:'on the contrary / rather' },
        { jp:'むしろ',          romaji:'mushiro',           en:'rather / instead' },
        { jp:'たしかに',        romaji:'tashika ni',        en:'certainly / admittedly' },
        { jp:'なるほど',        romaji:'naru hodo',         en:'I see / indeed' },
        { jp:'もっとも',        romaji:'mottomo',           en:'however / that said / indeed' },
        { jp:'ところが',        romaji:'tokoroga',          en:'however (unexpected)' },
        { jp:'それどころか',    romaji:'sore dokoro ka',    en:'far from that / on the contrary' },
        { jp:'しかも',          romaji:'shikamo',           en:'moreover / furthermore' },
        { jp:'それに',          romaji:'sore ni',           en:'besides / furthermore' },
        { jp:'ようするに',      romaji:'you suru ni',       en:'in short / to sum up' },
        { jp:'つまり',          romaji:'tsumari',           en:'in other words / that is' },
        { jp:'いわば',          romaji:'iwaba',             en:'so to speak / as it were' },
        { jp:'たとえば',        romaji:'tatoeba',           en:'for example' },
        { jp:'もとより',        romaji:'moto yori',         en:'from the start / of course' },
        { jp:'もちろん',        romaji:'mochiron',          en:'of course / naturally' },
    ],
    /* Ch 2 */  [
        { jp:'やりとげます',    romaji:'yari togemasu',     en:'accomplish / carry through' },
        { jp:'たちあがります',  romaji:'tachi agarimasu',   en:'stand up / rise' },
        { jp:'きりかえます',    romaji:'kiri kaemasu',      en:'switch / change over' },
        { jp:'とりかかります',  romaji:'tori kakarimasu',   en:'get started on / set about' },
        { jp:'もちあげます',    romaji:'mochi agemasu',     en:'lift up / raise' },
        { jp:'ふみこみます',    romaji:'fumi komimasu',     en:'step into / go deep into' },
        { jp:'おしつけます',    romaji:'oshi tsukemasu',    en:'force on / impose' },
        { jp:'うりこみます',    romaji:'uri komimasu',      en:'sell into / push into market' },
        { jp:'よびおこします',  romaji:'yobi okoshimasu',   en:'wake by calling / call up' },
        { jp:'はたらきかけます',romaji:'hataraki kakemasu', en:'approach / work on (s.o.)' },
        { jp:'いいのがします',  romaji:'ii nogashimasu',    en:'miss saying / let slip' },
        { jp:'ひきつけます',    romaji:'hiki tsukemasu',    en:'attract / draw in' },
        { jp:'うちあけます',    romaji:'uchi akemasu',      en:'confide / open up' },
        { jp:'おもいきります',  romaji:'omoi kirimasu',     en:'make up one\'s mind / go for it' },
    ],
    /* Ch 3 */  [
        { jp:'〜にしても〜にしても',romaji:'~ni shite mo ~ni shite mo',en:'whether ~ or ~' },
        { jp:'〜としても',      romaji:'~to shite mo',      en:'even if ~ / even assuming ~' },
        { jp:'〜どころか',      romaji:'~doko roku ka',     en:'far from ~ / not only ~ but' },
        { jp:'〜わりに（は）',  romaji:'~wari ni (wa)',      en:'for ~ / considering ~' },
        { jp:'〜とはいえ',      romaji:'~to wa ie',         en:'even so / nevertheless' },
        { jp:'〜くせに',        romaji:'~kuse ni',          en:'even though (disapproving)' },
        { jp:'〜ながら（も）',  romaji:'~nagara (mo)',      en:'while / although' },
        { jp:'〜においても',    romaji:'~ni oite mo',       en:'even in ~ / also in ~' },
        { jp:'〜うえ（に）',    romaji:'~ue (ni)',           en:'in addition / on top of that' },
        { jp:'〜ばかりか',      romaji:'~bakari ka',        en:'not only ~ but also ~' },
        { jp:'〜のみならず',    romaji:'~nomi narazu',      en:'not only ~ (formal)' },
        { jp:'〜はもとより',    romaji:'~wa moto yori',     en:'let alone ~ / not to mention ~' },
    ],
    /* Ch 4 */  [
        { jp:'〜かぎり',        romaji:'~kagiri',           en:'as long as ~ / as far as ~' },
        { jp:'〜にかぎって',    romaji:'~ni kagitte',       en:'precisely when ~ / only ~' },
        { jp:'〜かぎり（では）',romaji:'~kagiri (de wa)',    en:'as far as ~ / within the limits of ~' },
        { jp:'〜にかぎらず',    romaji:'~ni kagirazu',      en:'not limited to ~' },
        { jp:'〜さえ',          romaji:'~sae',              en:'even ~ / only ~' },
        { jp:'〜だけ',          romaji:'~dake',             en:'only ~ / just ~' },
        { jp:'〜だけあって',    romaji:'~dake atte',        en:'just as you would expect from ~' },
        { jp:'〜ほど',          romaji:'~hodo',             en:'to the extent that ~ / as ~ as' },
        { jp:'〜ほど〜ない',    romaji:'~hodo ~nai',        en:'not as ~ as ~' },
        { jp:'〜くらい（ぐらい）',romaji:'~kurai (gurai)',  en:'about ~ / approximately' },
        { jp:'〜ばかり',        romaji:'~bakari',           en:'only ~ / nothing but ~' },
        { jp:'〜のみ',          romaji:'~nomi',             en:'only ~ (formal)' },
    ],
    /* Ch 5 */  [
        { jp:'〜にしたがって',  romaji:'~ni shitagatte',    en:'as ~ / following ~ / in accordance with ~' },
        { jp:'〜にともなって',  romaji:'~ni tomonatte',     en:'along with ~ / accompanying ~' },
        { jp:'〜につれて',      romaji:'~ni tsurete',       en:'as ~ / in proportion to ~' },
        { jp:'〜によって',      romaji:'~ni yotte',         en:'depending on ~ / by means of ~' },
        { jp:'〜をつうじて',    romaji:'~wo tsuujite',      en:'through ~ / throughout ~' },
        { jp:'〜にかけて',      romaji:'~ni kakete',        en:'over a period of ~ / throughout ~' },
        { jp:'〜にわたって',    romaji:'~ni watatte',       en:'over ~ / spanning ~' },
        { jp:'〜にそって',      romaji:'~ni sotte',         en:'along ~ / in line with ~' },
        { jp:'〜にしたがい',    romaji:'~ni shitagai',      en:'in accordance with ~ (formal)' },
        { jp:'〜ようになります',romaji:'~you ni narimasu',  en:'come to ~ / reach the point where ~' },
        { jp:'〜ようにします',  romaji:'~you ni shimasu',   en:'make sure to ~ / try to ~' },
    ],
    /* Ch 6 */  [
        { jp:'おっしゃいます',  romaji:'osshaimasu',        en:'say (respectful)' },
        { jp:'おいでになります',romaji:'oide ni narimasu',  en:'be / go / come (respectful)' },
        { jp:'いらっしゃいます',romaji:'irasshaimasu',      en:'be / go / come (respectful)' },
        { jp:'ごらんになります',romaji:'goran ni narimasu', en:'look / see (respectful)' },
        { jp:'めしあがります',  romaji:'meshiagarimasu',    en:'eat / drink (respectful)' },
        { jp:'もうします',      romaji:'moushimasu',        en:'say / am called (humble)' },
        { jp:'まいります',      romaji:'mairimasu',         en:'go / come (humble)' },
        { jp:'おります',        romaji:'orimasu',           en:'be (humble)' },
        { jp:'いたします',      romaji:'itashimasu',        en:'do (humble)' },
        { jp:'はいけんします',  romaji:'haiken shimasu',    en:'look at / see (humble)' },
        { jp:'いただきます',    romaji:'itadakimasu',       en:'receive / eat / drink (humble)' },
        { jp:'さしあげます',    romaji:'sashiagemasu',      en:'give (humble)' },
        { jp:'うかがいます',    romaji:'ukagaimasu',        en:'visit / hear / ask (humble)' },
        { jp:'ぞんじます',      romaji:'zonjimasu',         en:'know (humble)' },
    ],
    /* Ch 7 */  [
        { jp:'こうれいか',      romaji:'koureika',          en:'aging / becoming older (society)' },
        { jp:'しょうしか',      romaji:'shoushika',         en:'declining birthrate' },
        { jp:'きんろうしゃ',    romaji:'kinrousha',         en:'worker / working person' },
        { jp:'きんろう',        romaji:'kinrou',            en:'labour / work' },
        { jp:'しつぎょう',      romaji:'shitsugyou',        en:'unemployment' },
        { jp:'こよう',          romaji:'koyou',             en:'employment' },
        { jp:'しょとく',        romaji:'shotoku',           en:'income' },
        { jp:'ぶっか',          romaji:'bukka',             en:'prices of goods' },
        { jp:'けいき',          romaji:'keiki',             en:'economic climate / business conditions' },
        { jp:'ふきょう',        romaji:'fukyou',            en:'recession / depression' },
        { jp:'こうきょう',      romaji:'koukyou',           en:'boom / prosperity' },
        { jp:'ぼうえき',        romaji:'boueki',            en:'trade (import/export)' },
        { jp:'ゆしゅつ',        romaji:'yushutsu',          en:'export' },
        { jp:'ゆにゅう',        romaji:'yunyuu',            en:'import' },
        { jp:'きぎょう',        romaji:'kigyou',            en:'enterprise / company' },
    ],
    /* Ch 8 */  [
        { jp:'ぎじゅつ',        romaji:'gijutsu',           en:'technology / technique' },
        { jp:'かがく',          romaji:'kagaku',            en:'science / chemistry' },
        { jp:'じっけん',        romaji:'jikken',            en:'experiment' },
        { jp:'けんきゅう',      romaji:'kenkyuu',           en:'research' },
        { jp:'はっけん',        romaji:'hakken',            en:'discovery' },
        { jp:'はつめい',        romaji:'hatsumei',          en:'invention' },
        { jp:'かいはつ',        romaji:'kaihatsu',          en:'development / R&D' },
        { jp:'じんこうちのう',  romaji:'jinkou chinou',     en:'artificial intelligence (AI)' },
        { jp:'データ',          romaji:'deeta',             en:'data' },
        { jp:'アルゴリズム',    romaji:'arugoritsumu',      en:'algorithm' },
        { jp:'ネットワーク',    romaji:'nettowaaaku',       en:'network' },
        { jp:'デジタル',        romaji:'dejitaru',          en:'digital' },
        { jp:'アナログ',        romaji:'anarogu',           en:'analogue' },
        { jp:'じどうか',        romaji:'jidouka',           en:'automation' },
        { jp:'かくしん',        romaji:'kakushin',          en:'innovation / reform' },
    ],
  ],

  /* ════════ N1 ════════ */
  N1: [
    /* Ch 1 */  [
        { jp:'おのずから',      romaji:'onozukara',         en:'naturally / by itself' },
        { jp:'いたって',        romaji:'itatte',            en:'extremely / very much' },
        { jp:'すこぶる',        romaji:'sukoburu',          en:'greatly / exceedingly' },
        { jp:'あいにく',        romaji:'ainiku',            en:'unfortunately' },
        { jp:'かたや',          romaji:'kata ya',           en:'on the other hand (literary)' },
        { jp:'しかるに',        romaji:'shikaru ni',        en:'however (literary)' },
        { jp:'なお',            romaji:'nao',               en:'furthermore / still / note that' },
        { jp:'ただし',          romaji:'tadashi',           en:'however / provided that' },
        { jp:'もっとも',        romaji:'mottomo',           en:'that said / however / most' },
        { jp:'あるいは',        romaji:'arui wa',           en:'or / perhaps' },
        { jp:'あながち〜ない',  romaji:'anagachi ~nai',     en:'not necessarily ~' },
        { jp:'あながち',        romaji:'anagachi',          en:'altogether / unconditionally' },
        { jp:'かろうじて',      romaji:'karoujite',         en:'barely / narrowly' },
        { jp:'ほうじて',        romaji:'houjite',           en:'duly / as expected' },
    ],
    /* Ch 2 */  [
        { jp:'むとんちゃく（な）',romaji:'mutonchaku (na)', en:'indifferent / unconcerned' },
        { jp:'ふてぶてしい',    romaji:'futebute shii',     en:'brazen / shameless' },
        { jp:'さしでがましい',  romaji:'sashide gamashii',  en:'presumptuous / meddlesome' },
        { jp:'もったいない',    romaji:'mottainai',         en:'wasteful / too good to waste' },
        { jp:'いたたまれない',  romaji:'ita tamarenai',     en:'can\'t bear to stay / unbearable' },
        { jp:'とりとめない',    romaji:'toritori menai',    en:'incoherent / rambling' },
        { jp:'なおざり（な）',  romaji:'naozari (na)',      en:'neglectful / careless' },
        { jp:'おざなり（な）',  romaji:'ozanari (na)',      en:'perfunctory / half-hearted' },
        { jp:'やむにやまれぬ',  romaji:'yamu ni yamarenou', en:'compelling / unavoidable' },
        { jp:'おもいがけない',  romaji:'omoi ga kenai',     en:'unexpected / unforeseen' },
        { jp:'かけがえのない',  romaji:'kakegae no nai',    en:'irreplaceable / invaluable' },
        { jp:'ゆるぎない',      romaji:'yurugi nai',        en:'unshakeable / firm' },
    ],
    /* Ch 3 */  [
        { jp:'〜にほかならない',romaji:'~ni hoka naranai',  en:'nothing but ~ / none other than ~' },
        { jp:'〜にすぎない',    romaji:'~ni suginai',       en:'merely ~ / nothing more than ~' },
        { jp:'〜こそ',          romaji:'~koso',             en:'(emphatic) precisely ~ / it is ~ that' },
        { jp:'〜からこそ',      romaji:'~kara koso',        en:'precisely because ~' },
        { jp:'〜てこそ',        romaji:'~te koso',          en:'only by doing ~ / it is only when ~' },
        { jp:'〜といったらない',romaji:'~to ittara nai',    en:'extremely ~ / cannot be more ~' },
        { jp:'〜というものだ',  romaji:'~to iu mono da',    en:'that\'s the way ~ is / that is what ~ means' },
        { jp:'〜というものではない',romaji:'~to iu mono de wa nai',en:'it\'s not that ~ / that doesn\'t mean ~' },
        { jp:'〜ものだ',        romaji:'~mono da',          en:'(natural) that\'s how it is / used to ~' },
        { jp:'〜ものではない',  romaji:'~mono de wa nai',   en:'one shouldn\'t ~ / it\'s not right to ~' },
        { jp:'〜ものがある',    romaji:'~mono ga aru',      en:'there is a sense that ~ / undeniably ~' },
    ],
    /* Ch 4 */  [
        { jp:'〜ゆえに',        romaji:'~yue ni',           en:'therefore ~ / because of ~ (literary)' },
        { jp:'〜がゆえに',      romaji:'~ga yue ni',        en:'precisely because ~ (literary)' },
        { jp:'〜に起因する',    romaji:'~ni kiin suru',      en:'be caused by ~ / stem from ~' },
        { jp:'〜に基づいて',    romaji:'~ni motozu ite',    en:'based on ~ / grounded in ~' },
        { jp:'〜をきっかけに',  romaji:'~wo kikkake ni',    en:'using ~ as a trigger / triggered by ~' },
        { jp:'〜を契機に',      romaji:'~wo keiki ni',      en:'taking ~ as an opportunity' },
        { jp:'〜の末（に）',    romaji:'~no sue (ni)',       en:'after ~ / as a result of ~' },
        { jp:'〜あげく（に）',  romaji:'~ageku (ni)',        en:'after much ~ / in the end (negative)' },
        { jp:'〜てはじめて',    romaji:'~te hajimete',      en:'only after doing ~ / not until ~' },
        { jp:'〜をもとに（して）',romaji:'~wo moto ni shite',en:'based on ~ / drawing from ~' },
        { jp:'〜に照らして',    romaji:'~ni terashite',     en:'in light of ~ / judged by ~' },
    ],
    /* Ch 5 */  [
        { jp:'〜にたえない',    romaji:'~ni taenai',        en:'cannot bear ~ / unbearable' },
        { jp:'〜にたえる',      romaji:'~ni taeru',         en:'worth ~ing / stand up to ~' },
        { jp:'〜にたりない',    romaji:'~ni tarinai',       en:'not worth ~ / beneath ~' },
        { jp:'〜にかなう',      romaji:'~ni kanau',         en:'meet ~ / suit ~' },
        { jp:'〜にそわない',    romaji:'~ni sowanai',       en:'not in keeping with ~ / not meet ~' },
        { jp:'〜ざるをえない',  romaji:'~zaru wo enai',     en:'cannot help but ~ / have no choice but ~' },
        { jp:'〜をよぎなくされる',romaji:'~wo yoginaku sareru',en:'be compelled to ~ / be forced to ~' },
        { jp:'〜かねない',      romaji:'~kanenai',          en:'might well ~ / could easily ~' },
        { jp:'〜かねる',        romaji:'~kaneru',           en:'find it difficult to ~ / can\'t bring oneself to ~' },
        { jp:'〜ないではいられない',romaji:'~nai de wa irarenai',en:'cannot help but ~ / can\'t stop ~ing' },
        { jp:'〜ずにはいられない',romaji:'~zu ni wa irarenai',en:'cannot help but ~ (literary)' },
    ],
    /* Ch 6 */  [
        { jp:'こっかい',        romaji:'kokkai',            en:'National Diet / Parliament' },
        { jp:'ぎかい',          romaji:'gikai',             en:'parliament / legislature' },
        { jp:'ないかく',        romaji:'naikaku',           en:'cabinet' },
        { jp:'せいさく',        romaji:'seisaku',           en:'policy / measure' },
        { jp:'はっき',          romaji:'hakki',             en:'display / exercise (of ability)' },
        { jp:'ほうあん',        romaji:'houan',             en:'bill (proposed law)' },
        { jp:'さいばん',        romaji:'saiban',            en:'trial / judicial proceedings' },
        { jp:'はんけつ',        romaji:'hanketsu',          en:'verdict / judgement' },
        { jp:'そしょう',        romaji:'soshou',            en:'lawsuit' },
        { jp:'べんご',          romaji:'bengo',             en:'defence (legal)' },
        { jp:'べんごし',        romaji:'bengoshi',          en:'lawyer / attorney' },
        { jp:'ひこく',          romaji:'hikoku',            en:'defendant' },
        { jp:'げんこく',        romaji:'genkoku',           en:'plaintiff' },
        { jp:'しょうこ',        romaji:'shouko',            en:'evidence / proof' },
        { jp:'むざい',          romaji:'muzai',             en:'not guilty' },
        { jp:'ゆうざい',        romaji:'yuzai',             en:'guilty' },
    ],
    /* Ch 7 */  [
        { jp:'こころ',          romaji:'kokoro',            en:'heart / mind / soul' },
        { jp:'いしき',          romaji:'ishiki',            en:'consciousness / awareness' },
        { jp:'むいしき',        romaji:'muishiki',          en:'unconscious / subconscious' },
        { jp:'ほんのう',        romaji:'honnou',            en:'instinct' },
        { jp:'りせい',          romaji:'risei',             en:'reason / rationality' },
        { jp:'かんせい',        romaji:'kansei',            en:'sensibility / sensitivity' },
        { jp:'じゅんすい（な）',romaji:'junsui (na)',        en:'pure / innocent' },
        { jp:'そんざい',        romaji:'sonzai',            en:'existence / being' },
        { jp:'かちかん',        romaji:'kachikan',          en:'values / sense of values' },
        { jp:'せかいかん',      romaji:'sekaikan',          en:'worldview / Weltanschauung' },
        { jp:'じんせいかん',    romaji:'jinseikan',         en:'view of life / philosophy of life' },
        { jp:'ほんしつ',        romaji:'honshitsu',         en:'essence / nature' },
        { jp:'げんしょう',      romaji:'genshou',           en:'phenomenon' },
        { jp:'しかく',          romaji:'shikaku',           en:'perspective / viewpoint' },
    ],
    /* Ch 8 */  [
        { jp:'さくひん',        romaji:'sakuhin',           en:'work (of art/literature)' },
        { jp:'げんさく',        romaji:'gensaku',           en:'original work' },
        { jp:'ちょしゃ',        romaji:'chosha',            en:'author / writer' },
        { jp:'ぶんたい',        romaji:'buntai',            en:'writing style' },
        { jp:'ひゆ',            romaji:'hiyu',              en:'metaphor' },
        { jp:'ぎじんほう',      romaji:'gijin hou',         en:'personification' },
        { jp:'ひかく',          romaji:'hikaku',            en:'comparison' },
        { jp:'えんきょく（な）',romaji:'enkyoku (na)',       en:'indirect / euphemistic' },
        { jp:'ちょくせつてき（な）',romaji:'chokusetsuteki (na)',en:'direct' },
        { jp:'ひょうげん',      romaji:'hyougen',           en:'expression' },
        { jp:'かんかく',        romaji:'kankaku',           en:'sense / sensation / feeling' },
        { jp:'びてき（な）',    romaji:'biteki (na)',        en:'aesthetic' },
        { jp:'そうぞう',        romaji:'souzou',            en:'imagination / creation' },
        { jp:'かんどう',        romaji:'kandou',            en:'deep emotion / moving' },
        { jp:'きょうかん',      romaji:'kyoukan',           en:'empathy / sympathy' },
    ],
  ],

};

window.NZChapterVocabWords = NZChapterVocabWords;
